### ISSUE TITLE
[ENTREGUES] Sessió 3: 16 de Novembre de 2015

### ISSUE THREAD

**Issue by amaiasalvador** [gdsa-upc/gdsa-suport#1]
Responeu (abans del termini) amb el nom del vostre equip i l'enllaç públic a la presentació a Google Drive.

**Comment by Christiancuz** [comment]
GRUPO 101.2
 Enlace  https://drive.google.com/open?id=0B1qNyUzI_7jvSlhKQ1NsR1NvWTA
 se encuentra la presentación y las fotos correspondientes del grupo.

**Comment by monicachs** [comment]
GRUP 102.1 entrega S3
[https://drive.google.com/open?id=1j4XhgKo5sl_OgJhbl1cTukef9B3PBcNmTa4dFhrjFWE](https://drive.google.com/open?id=1j4XhgKo5sl_OgJhbl1cTukef9B3PBcNmTa4dFhrjFWE)
En aquest enllaç està la presentació de la primera entrega del nostre projecte i l'enllaç al fitxer .zip amb les fotografies corresponents al nostre grup.

**Comment by sadek4** [comment]
Grup 102.3
Aquí us deixem el link de la presentació on trobareu el link de descàrrega de les imatges i de la pàgina web.

https://docs.google.com/presentation/d/1HGoqArL-gAcIB__nBO2e-Mi_Ecp_ghk-1d-QixOEk80/edit#slide=id.p5

**Comment by marcllado95** [comment]
Grup 101.1
Us deixem l'enllaç a la presentació:
https://drive.google.com/open?id=1nhOBICOFf1w9uZaILL3p_XdLangvuzF6UWGSWky7ajw

**Comment by AZarzuela** [comment]
Grup 102.2
Enllaç a la nostra presentació:

https://docs.google.com/presentation/d/1UQkgzAHqpysHhPx3SxVPNIe3HJe3eVFkrqmfDar_0cs/edit#slide=id.p

**Comment by GaryKitkat7** [comment]
Entrega 101.3
https://docs.google.com/presentation/d/1y8AO40tSNNFS2W8vv64103Qf8HmJJEGACGmZHAMxRzA/edit#slide=id.p

**Comment by amaiasalvador** [comment]
Grups @gdsa-upc/101-1 , @gdsa-upc/102-2 i @gdsa-upc/101-3 : feu públiques les vostres presentacions o doneu-nos-hi accés ! No les podem veure.

**Comment by sergisantana** [comment]
La presentació del grup 101.1 ja està activada. Ens faltava posar-ho públic. Gràcies!

**Comment by SergiBadia** [comment]
Grup 101.3
Ara s´hauria de poder veure: https://docs.google.com/presentation/d/1y8AO40tSNNFS2W8vv64103Qf8HmJJEGACGmZHAMxRzA/edit?usp=sharing

**Comment by carlesm95** [comment]
Grup 102.2
La nostra presentació sempre ha estat pública.
