### ISSUE TITLE
[ENTREGUES] Sessió 4: 23 de Novembre de 2015

### ISSUE THREAD

**Issue by amaiasalvador** [gdsa-upc/gdsa-suport#10]
En [aquest link](https://docs.google.com/presentation/d/1X3lrU1k5UNDIU8KTiLllCRD8jQOmRKKw6rmYToag3ek/edit?usp=sharing) podeu trobar les slides de la sessió 3 del 17 de Novembre de 2015. 

De cara a l'entrega, responeu en aquest mateix issue (abans del termini) amb el nom del vostre equip i l'enllaç públic a la presentació a Google Drive.

**Comment by Christiancuz** [comment]
International-Team
https://drive.google.com/open?id=1SLZ9TB9MvtV5pc9gkRrgDZpBRgSm8zFbycGWD3QV--8

**Comment by GaryKitkat7** [comment]
Entrega Sessió 4: Discover-Terrassa
https://docs.google.com/presentation/d/1w244aRi2Anlm4fqflLytP_GPiFlsBMz11oWJanORoJs/edit?usp=sharing

**Comment by mateomv92** [comment]
Entrega sessió 4: RdE
https://docs.google.com/presentation/d/1GRpN6P3TXzz9qjlJMRnuTnzOCgWWnYrGAsc7z7_9vqw/edit#slide=id.gd88819bae_0_29

**Comment by monicachs** [comment]
Entrega sessió 4, grup 102.1 (Building-Recognizer):
https://docs.google.com/presentation/d/1vaIgvMihRCzGw4zdUQQOoQhxdtMMelmlG6Q2tIG4MpU/edit#slide=id.gd92b9f130_2_0

**Comment by marcllado95** [comment]
What-a-Building-App (Grup 101.1)
Entrega sessió 4:
 https://docs.google.com/presentation/d/1eWARLhBUta1__Fkso_XZCJwunTnInZsQYMJ8I9ivgh8/edit?usp=sharing

**Comment by AZarzuela** [comment]
Entrega sessió 4, grup 102.2 - Egara-View:
https://docs.google.com/presentation/d/1X9lsa4J0dgTWFJqQlZZJmJJLbvQBP_AtPHRmMvx8zno/edit?usp=sharing
