### ISSUE TITLE
Error a l'hora d'engegar Jupyter

### ISSUE THREAD

**Issue by AVillegas8** [gdsa-upc/gdsa-suport#100]
Quan executo les comandes per obrir Jupyter, em salta un error.

![image](https://user-images.githubusercontent.com/44750583/48896122-22e01680-ee47-11e8-830b-53d9f294ad00.png)

**Comment by noe** [comment]
https://stackoverflow.com/a/49587145/674487

**Comment by AVillegas8** [comment]
Una vegada executo 'gcloud auth login' i afegeixo el codi, torno a executar les comandes per connectar a Jupyter però no ho aconsegueix.

![openfailedjupyter](https://user-images.githubusercontent.com/44750583/48903360-9db32c80-ee5b-11e8-88d9-1b91828312c1.PNG)

**Comment by noe** [comment]
From https://cloud.google.com/dataproc/docs/concepts/accessing/cluster-web-interfaces:

![image](https://user-images.githubusercontent.com/4972/48904519-ecae9100-ee5e-11e8-92ca-85d8752fc66d.png)

**Comment by AVillegas8** [comment]
Quan intento ajustar les variables, segons el que demana, em dona un error en el PROJECT_ID

![openfailedjupyter2](https://user-images.githubusercontent.com/44750583/48906086-ae67a080-ee63-11e8-8c0b-05f1bd9fb3c7.PNG)

**Comment by noe** [comment]
La sintaxi que estàs fent servir és del shell de Windows, no de sh, bash, etc.

En lloc de `%XXX%`, fes servir la sintaxi `$XXX`

**Comment by AVillegas8** [comment]
Segueix sense tirar.
![openfailedjupyter3](https://user-images.githubusercontent.com/44750583/48908295-2afd7d80-ee6a-11e8-86ef-43687952a82e.PNG)

**Comment by noe** [comment]
https://www.youtube.com/watch?v=Y6_7xaxkPik
