### ISSUE TITLE
Error amb Jupyter

### ISSUE THREAD

**Issue by AlexLopezPedrosa** [gdsa-upc/gdsa-suport#102]
Seguint els passos per connectar amb "Jupyter LAB" ens dona aquest error:

![captura de pantalla 2018-11-22 a las 13 17 54](https://user-images.githubusercontent.com/45073194/48902578-43b16780-ee59-11e8-8b8a-21e0800dc6ae.png)

**Comment by noe** [comment]
https://github.com/gdsa-upc/gdsa-suport/issues/100

https://github.com/gdsa-upc/gdsa-suport/issues/101
