### ISSUE TITLE
Coupon Limit Exceedded

### ISSUE THREAD

**Issue by YuBai94** [gdsa-upc/gdsa-suport#104]
The maximum number of coupons redeemed for this course has been exceeded. we can not get our 50$

**Comment by xavigiro** [comment]
No em queda clar en quin moment us apareix aquest missatge, però crec que té a veure amb un problema que just hem detectat també aquesta setmana al curs de DLAI de Barcelona. Es veu que GCloud no permet que un mateix compte utilitzi més de tres cupons de descompte. Intueixo que la lògica que hi ha darrera és que no hi hagi estafes, de forma que algú demani molts cupons per repartir entre estudiants, però que després els utilitzi per alguna altra fi des d'un únic compte.

La solució és de fet el que alguns de vosaltres ja esteu implementant "sense voler": vau definir les instàncies pendent d'un compte personal, i després el que feu és habilitar la facturació d'aquella instància sobre altres comptes de Google. Aquesta opció està descrita en [aquest document](https://docs.google.com/document/d/1yOu9lH5re9lSSLC1usw4YyDEB2eNCk0JefhvaW-4f_c/edit?usp=sharing) de GCloud que ens han fet arribar per explicar com gestionar el nou sistema de cupons per a grups de treball. Us heu de fixar amb el "Approach 2: any sized group". Fixeu.vos que per fer el canvi de facturació entre usuaris, caldrà desactivar la primera facturació.

Ho proveu i em dieu si us funciona ?
