### ISSUE TITLE
SDK Could not fetch resource

### ISSUE THREAD

**Issue by YuBai94** [gdsa-upc/gdsa-suport#105]
C:\Users\Pepito\AppData\Local\Google\Cloud SDK>gcloud compute ssh --project gdsa-2018-team-3 --zone us-west1-b tensorflow-1-vm -- -L 8080:localhost:8080
ERROR: (gcloud.compute.ssh) Could not fetch resource:
 - The resource 'projects/gdsa-2018-team-3/zones/us-west1-b/instances/tensorflow-1-vm' was not found

Our VM is set in us-west1-b 
Our Project ID is gdsa-2018-team-3
The VM was started when we send this code in SDK

**Comment by rodrigoarcos** [comment]
Same problem here

**Comment by rodrigoarcos** [comment]
Yu, donde pone "tensorflow-1-vm" tienes que poner el nombre de tu instancia, quizás es ese el problema.

**Comment by YuBai94** [comment]
Si, aparte de eso no tenia VM iniciado. 

Gracias
