### ISSUE TITLE
upload files from Gcloud

### ISSUE THREAD

**Issue by martiollea** [gdsa-upc/gdsa-suport#108]
We've uploaded the Terrassa Buildings database into a Bucket from GCloud. We don't know how to upload these files from the Bucket to the Jupyter notebook.

**Comment by xavigiro** [comment]
Aquest tema va sortir l'altre dia a classe i vam dir de NO utilitzar el Bucket, ja que això complicava la vida. Ho teniu a partir de la pàgina 57 dels [informes per la sessió 4](https://docs.google.com/presentation/d/15yCi-gsnwulwqrJAmqalac7hPqDu4U2RHOJE-pPyhh4/edit?usp=sharing).

Crec que teniu dues opcions:

a) (preferida) Des de la mateixa consola de la màquina virtual, amb un wget i unzip.

b) Carregant el fitxers des de la Notebook tal com vau fer amb la pràctica 0a i després fent una crida a sistema des de la notebook per fer l'unzip.

Tanqueu el tiquet si queda resolt.
