### ISSUE TITLE
Sessió 4 - Equip 6

### ISSUE THREAD

**Issue by MarcArriaga** [gdsa-upc/gdsa-suport#115]
[Presentació](https://docs.google.com/presentation/d/1uiSEykragLDGuEQRcblD5zB0nm2IYF1KvjylajNP9iw/edit?usp=sharing) de l'equip 6

**Comment by xavigiro** [comment]
No hi tinc accés.

**Comment by MarcArriaga** [comment]
Torno ha intentar-ho 

[Link](https://docs.google.com/presentation/d/1uiSEykragLDGuEQRcblD5zB0nm2IYF1KvjylajNP9iw/edit?usp=sharing)

**Comment by xavigiro** [comment]
Ara sí !
