### ISSUE TITLE
Sessió 2 - Equip 1

### ISSUE THREAD

**Issue by lauramontolio** [gdsa-upc/gdsa-suport#116]
Enlace a la presentación https://docs.google.com/presentation/d/1vx4Izqg1SpJN2GqfzIFjlR_sK9iqKRIOzYpToTCI14k/edit#slide=id.g4607fc9278_1_44

**Comment by xavigiro** [comment]
No hi tinc accés.

**Comment by lauramontolio** [comment]
Ara en teoria si.

El 23 nov 2018, a las 15:20, Xavier Giro-i-Nieto <notifications@github.com<mailto:notifications@github.com>> escribió:


No hi tinc accés.

**Comment by xavigiro** [comment]
Ara sí.
