### ISSUE TITLE
Instruccions de cara a la sessió #5 (2018)

### ISSUE THREAD

**Issue by xavigiro** [gdsa-upc/gdsa-suport#117]
[Aquí](https://docs.google.com/presentation/d/1-iVsMaYSKsFEX6Zk7Ruc2U8B5QD-E9AWddhTr8_7scc/edit?usp=sharing) teniu les instruccions de cara a la sessió 5.

**Comment by MarcArriaga** [comment]
Bona tarda @xavigiro ,

Podries posar el power per poder pujar les presentacions?

Moltes gracies i disculpa les molesties.

**Comment by xavigiro** [comment]
Hola @MarcArriaga , disculpa el retard. Ja podeu afegir les vostres pàgines d'informe en [aquesta presentació compartida](https://docs.google.com/presentation/d/10sx-lJHMb_CuAeZYhD5b_pfd6zo0xXTGVI5cKx0Drx0/edit?usp=sharing).
