### ISSUE TITLE
Cerca Visual

### ISSUE THREAD

**Issue by manelsalva** [gdsa-upc/gdsa-suport#119]
En el moment que ja tenim la matriu amb els descriptors de totes les imatges de train, test i val, quin seria el procediment per a poder realitzar la cerca visual?
Gracies.

**Comment by Zhomas06** [comment]
En teoría te pide hacer dos búsquedas. Una con una agen de val y las imagenes de train. La otra es utilizando todas las imagenes de val y las de train.
Es prácticamente adaptar el codigo de la práctica 0b al codigo que ya tienes
