### ISSUE TITLE
IndexError: index 717 is out of bounds for axis 0 with size 64

### ISSUE THREAD

**Issue by JoanIgnasiMarti** [gdsa-upc/gdsa-suport#122]
![image](https://user-images.githubusercontent.com/44504641/49478769-0a95d180-f821-11e8-9afe-02695b581e29.png)
No sabem el motiu de l'error a l'hora de mostrar els resultats, adjunto codi i error. No sabem d'on surt el 717 ja que no és cap múltiple dels index que estem emprant.

**Comment by Zhomas06** [comment]
Una pregunta, tus imagenes las tienes de 64 x 64 ? Porque, si las tienes de 224 x 224  la h y la w deberían valer 224. Por otro lado cuidado con la cantidad de offset que pongas, 900 de offset lo veo un poco grande, prueba con un offset de 20. 
Ya comentarás si te funciona.
T.

**Comment by JoanIgnasiMarti** [comment]
Mismo error

![captura](https://user-images.githubusercontent.com/44504641/49505532-4316c900-f87c-11e8-853e-2410ff73916f.PNG)

**Comment by Zhomas06** [comment]
Estás seguro de estar redimensionando las imagenes de entrada?

**Comment by santimundi** [comment]
fijate en los parentesis de la línea que te marca error, creo que estan mal, la parte de (h*1-...) esta dentro de image.paste()
