### ISSUE TITLE
Syntax error en la cerca visual 

### ISSUE THREAD

**Issue by hedo95** [gdsa-upc/gdsa-suport#123]
Mostrem el codi de la cerca visual que hauría de mostrar les imatges de la cerca però sense aquesta part solucionada no podem saber si funcionen les funcions de Recall etc...
 
Codi: 

h,w = (224,224)
#hay que hacer que muestre las imagenes
new_image = Image.new('RGB',(h*5,w*1))
offset = 10
test_list = []
train_list = []
train_dir = './base_de_dades/train/images/'#cambiar por test,var y train
train_image_names = os.listdir(train_dir)
train = np.array(Image.new('RGB',(h,w)))
for file in train_image_names:
    dir2 = os.path.join(train_dir,file)
    if dir2 != './base_de_dades/train/images/.ipynb_checkpoints':
        img = np.array(image.load_img(dir2,target_size=(h,w)))
        train_list.append(img)

test_dir = './base_de_dades/test/images/'#cambiar por test,var y train
test_image_names = os.listdir(test_dir)
test = np.array(Image.new('RGB',(h,w)))

for file in test_image_names:
    dir2 = os.path.join(test_dir,file)
    if dir2 != './base_de_dades/test/images/.ipynb_checkpoints':
        img = np.array(image.load_img(dir2,target_size=(h,w)))
        test_list.append(img)
        
for q in range(1):
    ranks_q = ranks[q*(offset+1),:]
    for i in range(5):
        index = int(ranks_q[i])
        new_image.paste(Image.fromarray(x_train_img[index]), (h*(1+i),w*q)
    
    
    indice=offset+1
    indice = q*indice
    ima_q = Image.fromarray(x_val_img[indice])
    #ima_q = Image.fromarray(x_val_img[q*(offset+1),...])
    ima_q = ImageOps.expand(ima_q, border=3, fill = 'green')
    
    new_image.paste(ima_q, (0,w*q))
    
plt.imshow(new_image)
plt.axis('off')
plt.show()

**Missatge d'error: **

File "<ipython-input-42-3f762278d218>", line 33
    indice=offset+1
         ^
SyntaxError: invalid syntax

**Comment by xavigiro** [comment]
En aquesta línia en concret no hi veig res d'estrany. Potser us heu fet un embolic en algun parèntesi o cometa ? Per trobar-ho aneu comentant trossos de codi i executant, fins a aïllar el problema i resoldre'l.

**Comment by xavigiro** [comment]
Heu pogut resoldre aquest problema '
