### ISSUE TITLE
Instruccions de cara a la sessió 7 (2018)

### ISSUE THREAD

**Issue by xavigiro** [gdsa-upc/gdsa-suport#124]
Aquí teniu les [instruccions](https://docs.google.com/presentation/d/1pr-xuzuFvh9i5iJO3CmMWwmqOVjKW3YPzyA0Hh6ayJs/edit?usp=sharing) de cara a la sessió 7.

**Comment by MarcArriaga** [comment]
Equip 6
[Link](https://github.com/gdsa-upc/2018-Equip6/issues/1) al nostre repositori on trobaràs la presentació.

**Comment by YuBai94** [comment]
Entrega[ Equip7](https://docs.google.com/presentation/d/1cV80o2JNB0Rn0-C7nHlEDWuTfNT3l8XIXCdmm8Y6YWk/edit?usp=sharing)

**Comment by punti05** [comment]
Presentació [Equip 5](https://docs.google.com/presentation/d/1ZArAzHVi39aoPu2Kq4Qce7cKiMAZDabMIl-LpdtRkJE/edit?usp=sharing)

**Comment by rodrigoarcos** [comment]
Presentación [Equip 2](https://docs.google.com/presentation/d/16Qf9Ao4ZI_R_Pb_4SVHT6Q3qQpbZp8jNFjhSXcNgCZo/edit#slide=id.gcb9a0b074_2_0)

**Comment by lauramontolio** [comment]
Presentació [Equip1](https://docs.google.com/presentation/d/1McQtvQ05x1mV_Zlx_r8AhfkDiHkAVZ2Uu5sVw8YxfHs/edit?usp=sharing)

**Comment by monicaclemente** [comment]
Presentació [Equip4](https://docs.google.com/presentation/d/1ITy-j9QaGP6V7BCxcS_EuSmuNk0mNHMQIdEk97hE8X4/edit?usp=sharing)

**Comment by annaarbiol** [comment]
Presentació [Equip3](https://prezi.com/view/shdnJT28MHcQLtp0SoKg/)
