### ISSUE TITLE
Kaggle

### ISSUE THREAD

**Issue by Paumaza** [gdsa-upc/gdsa-suport#125]
Bona tarda, 

No he aconseguit trobar la competició del kaggle del 2018, entenc que no estsà activa encara, la podries activar per a que poguem començar a penjar resultats i fer proves?

Moltes gràcies

**Comment by xavigiro** [comment]
Acabo d'[engegar-la](https://www.kaggle.com/c/terrassa-buildings-2018/). Hi havia una part de la configuració que m'ha costat més del que m'esperava.
