### ISSUE TITLE
Exemple format entrega Kaggle

### ISSUE THREAD

**Issue by manelsalva** [gdsa-upc/gdsa-suport#126]
Al Kaggle posa que hi ha un fitxer .csv de mostra anomenat kaggle_rnd_bl.csv per a poder descarregar, algú l'ha aconseguit descarregar?

**Comment by Zhomas06** [comment]
A nuestro grupo también le gustaría que se añadiese el archivo kaggle_rnd_bl.csv, ya que es algo difícil entregarlo sin el ejemplo.

**Comment by xavigiro** [comment]
Ja ho teniu pujat al Kaggle, al mateix lloc on hi ha les imatges.
