### ISSUE TITLE
responeu a aquest fil amb la vosta presentació pel dia de l'examen

### ISSUE THREAD

**Issue by xavigiro** [gdsa-upc/gdsa-suport#127]
[Aquí](https://docs.google.com/presentation/d/1MqbaUsLVDnmV3M7J29_OltdIIaSRLQjyBscUBKC7VSI/edit?usp=sharing) teniu les instruccions de l'examen final.

Indiqueu l'ID de l'equip en la vostra resposta quan pengeu la vostra presentació.

**Comment by punti05** [comment]
Presentació examen final
https://docs.google.com/presentation/d/18wwGmtRI5YlY9aET_rLPzDbeWEEdf9yeOUxJaP0v9tE/edit?usp=sharing

**Comment by lauramontolio** [comment]
[Presentació](https://docs.google.com/presentation/d/1-0rNJtdMKbLpATfQSQPIDHinPjsjO0_RrabwO1eja5k/edit?usp=sharing) examen final

**Comment by xavigiro** [comment]
Hola @punti05 : la vostra presentació no és pública. Si us plau canvieu els permisos de document.

**Comment by JudithFont** [comment]
Equip 6 [Presentació final](https://docs.google.com/presentation/d/1r8LPciAKj2SMJoutf1SS226qdVJzKa29x0FECp5sQsg/edit#slide=id.g33bace5839_0_0)

**Comment by rodrigoarcos** [comment]
[Presentació](https://docs.google.com/presentation/d/11CmjY2kcLBKK5VEhEuKxx2PomnoI_9A_F02Z12GYhR0/edit#slide=id.g1f87997393_0_1544) final Equip 2

**Comment by YuBai94** [comment]
EQUIP 7 ([LINK](https://docs.google.com/presentation/d/1gnvZUaDPsuJrvvU6z7fkhFzgqF0akT1Z5iFtKrQu42o/edit?usp=sharing))

**Comment by monicaclemente** [comment]
[Presentació equip 4](https://docs.google.com/presentation/d/16-PBAFN1aTKSdNhf6kGC2TZtBXjPsdZrwgo8yxI_tek/edit?usp=sharing)

**Comment by annaarbiol** [comment]
[Equip 3](https://prezi.com/p/nrobf90dtgr7/)
