### ISSUE TITLE
Error de facturació

### ISSUE THREAD

**Issue by hedo95** [gdsa-upc/gdsa-suport#129]
Hola,

Ens dona un error de facturació en la VM del grup 1. Necessitem més GPU's?

![whatsapp image 2019-01-05 at 00 19 08](https://user-images.githubusercontent.com/44504802/50725211-86be5600-10fa-11e9-89d9-7d8b0792e1d8.jpeg)

**Comment by xavigiro** [comment]
Hauríeu de donar més detalls.

Vau seguir la configuració que us vaig recomanar a les instruccions de la [sessió 4](https://docs.google.com/presentation/d/1VkCrU1orc7-nE6p6szww6v9WqEWzvSLF7Ms12C19Ip4/edit?usp=sharing) ?
