### ISSUE TITLE
Error de facturación en google cloud

### ISSUE THREAD

**Issue by JoanIgnasiMarti** [gdsa-upc/gdsa-suport#130]
![image](https://user-images.githubusercontent.com/44504641/50978399-9ff94500-14f4-11e9-8a2b-eead865eb7bd.png)
Llevamos una semana con este problema sin respuesta, resulta que nos indica que no hemos gastado créditos pero aun asi no se nos permite acceder a nuestro proyecto, ocurrió de un día para el siguiente y nos gustaría saber la solución dado que no da tiempo a rehacer todo el proyecto desde cero. Muchas gracias.
Hemos intentado contactar con el profesor sin resultado alguno y empezamos a desesperarnos.

**Comment by JoanIgnasiMarti** [comment]
Ni siquiera el soporte de google nos responde.

**Comment by xavigiro** [comment]
No vau posar cap alerta perquè us avisés quan s'estaven acabant el crèdit ? Teníeu configurada la màquina tal com indicaven les [instruccions de la sessió 4](https://docs.google.com/presentation/d/1VkCrU1orc7-nE6p6szww6v9WqEWzvSLF7Ms12C19Ip4/edit?usp=sharing) ?

Hauríeu de donar més detalls.
