### ISSUE TITLE
Loss Negativa

### ISSUE THREAD

**Issue by manelsalva** [gdsa-upc/gdsa-suport#131]
Hem seguit les instruccions donades per a generar el model amb les nostres imatges i al generar-lo a la funció fit_generator ens dona un loss negatiu i un accuracy bastant baix, com podem solucionar-ho?

![image](https://user-images.githubusercontent.com/43412429/51074529-897ff480-1680-11e9-81a0-e0563bf662d7.png)

**Comment by xavigiro** [comment]
Per intentar ajudar-vos hauríeu de compartir el vostre codi, en una llibreta idealment per tal que es pugiu entendre tot el que feu. També hauríeu d'indicar quines instruccions esteu seguint. 

No és possible ajudar-vos amb aquesta poca informació, però així a priori sembla que no esteu passant a l'entrador les dades necessàries.

**Comment by manelsalva** [comment]
Adjunto el [codi](https://github.com/gdsa-upc/2018-Equip7/blob/master/ModelGenerator.ipynb) amb el que generem el model.
Les nostres imatges amb les que generem el model i l'entrenem estan a una carpeta Data, amb dues subcarpetes Valid i Train, on a cadascuna hi han subcarpetes dividint les imatges segons de quin edifici són, menys els desconeguts.
Estem carregant be les dades?, ens diu que troba quantes classes son pero ens segueix donant una acc molt petita.
