### ISSUE TITLE
Repetició de valors en el fitxer .csv

### ISSUE THREAD

**Issue by MGarcia99** [gdsa-upc/gdsa-suport#134]
Hola,

Tenim un problema a l'hora de crear el fitxer .csv
El tema és que en principi (tal i com es diu al Kaggle), es necessita un fitxer amb 2066 files (1 de capçalera i 2065 amb els valors). El nostre problema arriba amb les 4 últimes files, ja que són repeticions de les 4 primeres i no ens deixa penjar el fitxer.
Hem suposat que database (2065 imatges) correspon a les imatges de TRAIN i queries (2061 imatges) a l'apartat de QUERIES.

<img width="842" alt="Captura de Pantalla 2020-01-09 a les 18 44 39" src="https://user-images.githubusercontent.com/57806175/72091288-19965f80-3310-11ea-9f93-36c6d2bf52b1.png">

**Comment by xavigiro** [comment]
Gràcies per identificar aquest problema, que està en les dades i tal com les vaig etiquetar. Crec que ara està resolt. Us explico els motius i la solució:

MOTIU
A nivell de concepte, em va semblar més raonable donar-vos l'anotació de les dades que ja estan a la base de dades. A més, era més directe perquè ho comparéssiu amb el codi de l'Eva, que també fa referència a database.txt. El problema és que això no lliga amb els fitxers que hi ha pujats al Kaggle, ja que espera que justament feu la cerca sobre les particions de validació+testt, i que les cerques es realitzin amb dades d'entrenament per les quals teniu la seva anotació.

SOLUCIÓ
Doncs la solució ha estat capgirar les dades que trobareu al Kaggle. He intercanviat les particions de les dades i crec que ara ja encaixa tot. Potser el més fàcil és que descarregueu les dades de nou del mateix Kaggle. Però si voleu fer-ho manualment vosaltres, és qüestió d'intercanviar els papers entre les dues particions. Quan ho feu ja obtindreu resultats amb 2065 files + 1 fila de capçalera.

Ho comproveu i, si està resolt, llavors tanqueu aquest issue ?

**Comment by xavigiro** [comment]
En el issue #136 s'ha explicat que de fet l'errada no estava en les dades sinó en un altre punt. Així doncs, he refet la partició original. Ja la podeu trobar al Kaggle.

Comproveu que quadri i, si no és així, reobriu aquest issue.
