### ISSUE TITLE
Problema al pujar els resultats al kaggle

### ISSUE THREAD

**Issue by MGarcia99** [gdsa-upc/gdsa-suport#135]
Bona tarda,

Amb l’Equip 2 hem tingut un petit problema. Resulta que he intentat pujar els resultats al kaggle però no surt l'opció de pujar cap resultat, només et deixa veure els resultats que has penjat (anteriorment teníem una pestanya que ens portava directament a la secció per pujar els resultats). Llavors he eliminat el meu compte i n’he creat un de nou amb el correu de la universitat (cosa que no havia fet abans i pensant que l’error podria venir per aquí), però resulta que ara que els meus companys no es poden unir a l’equip perquè jo n’era el leader. Hi ha alguna manera que puguis eliminar els equips 2?

D’altre banda, tal i com he comentat, a cap membre de l’equip ens deixa pujar resultats, ni utilitzant l’API. No sé si és un error temporal o s’ha de fer d’alguna altra manera.

Disculpa les molèsties,

Equip 2

<img width="947" alt="Captura de Pantalla 2020-01-13 a les 16 17 20" src="https://user-images.githubusercontent.com/57806175/72268338-ed395680-3621-11ea-8dc1-11af82721e83.png">

**Comment by xavigiro** [comment]
Ja està resolt. Quan havia modificat el número de línies a processar per calcular els resultats, el sistema havia esborart el fitxer de solucions que tenia, i l'he hagut de pujar de nou. Ja podeu tornar a enviar resultats.
