### ISSUE TITLE
Error issue #134

### ISSUE THREAD

**Issue by MGarcia99** [gdsa-upc/gdsa-suport#136]
Hola,

En l'issue #134, comentàvem que havíem tingut un problema amb la base de dades, i es va intentar capgirar les dues carpetes per tal de trobar la sol·lució.
Al final, però, resulta que les carpetes originals ja estaven bé: 2065 --> Queries i 2061 --> Database (ja que es necessita 2065 files de queries en el fitxer .csv).
Ho comentem perquè al final l'error que teníem no era de la base de dades, sinó de com capturàvem el nom les imatges i era per aclarar-ho.

Gràcies,

Equip 2

**Comment by xavigiro** [comment]
He doncs reanomenat les dues carpetes i generate un nou queries.txt. Ja està disponible al Kaggle. Si us plau comproveu que ara quadri tot i, si no fos el cas, reobriu l'issue #134 (no seguiu amb aquest en paral·lel que pot confondre).
