### ISSUE TITLE
[DUBTE] Build database

### ISSUE THREAD

**Issue by carlesm95** [gdsa-upc/gdsa-suport#14]
A la funció build database hem de passar-li un unic path on es trobin totes les imatges de training i validation o li passem dos paths, un amb la ruta de les imatges de validation i una altra amb la de les de training?
I a la sortida de la funció, hem de fer dos .txt on un contingui les ID de les imatges de training i un altre les de validation o fem un unic .txt que contingui les ID de totes les imatges?

**Comment by xavigiro** [comment]
Només heu de posar-li un path.

La idea és que crideu a la funció dues vegades, una per les imatges d'entrenament i una segona vegada per les imatges de validació. En el futur, hi haurà una tercera vegada, que serà quan us donarem les imatges de prova.

Un tema diferent és com li voleu introduir aquest path. Podeu fer-ho amb un fitxer de paràmetres que cada usuari tingui en el seu directori local, indicant on estan desades les imatges. Malgrat que no ho he fet mai amb Python, crec que es podria fer amb aquest [ConfigParser](https://docs.python.org/2/library/configparser.html) ([exemples](https://wiki.python.org/moin/ConfigParserExamples)).

**Comment by carlesm95** [comment]
Llavors la funció també ha de fer dos .txt diferents no?

**Comment by xavigiro** [comment]
La funció ha de fer un .txt, però cridareu la funció dues vegades, una vegada per cada conjunt de dades. Així al final tindreu dos fitxer de text.

Si no veiéssiu clar el tema del ConfigParser, podeu crear un script amb la funció que us indico i també amb una funció [main](https://docs.python.org/3/library/__main__.html). En aquest cas, quan executeu l'script el que es farà seria executar el main. En el main llavors podeu cridar dues vegades la funció.

Ens hem entès millor ara ? Si és així, tanca el tiquet (el reobro perquè em sembla que no havia quedat clar). Si no s'ha entès, mira d'explicar-me millor el dubte que teniu.
