### ISSUE TITLE
[DUBTE] Random classification possible labels

### ISSUE THREAD

**Issue by FcoOrtiz** [gdsa-upc/gdsa-suport#15]
A la funció Random classification, el parámetre d'entrada de labels que es exactament?
Un txt d'on llegim les possibles labels?

**Comment by xavigiro** [comment]
Bona pregunta. Ja us deveu haver fixat que està en vermell, perquè us volíem donar una certa llibertat.

Quan tingueu el sistema acabat, aquesta entrada serà el model de les vostres classes. És a dir, la informació que us permetrà classificar una imatge entre una classe o una altra. A aquestes altures del projecte, però, encara no us hem demanat que entreneu cap model, així que ho vam deixar una mica obert justament perquè us féssiu aquest pregunta. Així doncs, bones notícies: aneu pel bon camí.

Tal com tu proposes, aquesta setmana en que assigneu les etiquetes de les classes de forma aleatòria, en teniu prou amb un fitxer de text que justament contingui les etiquetes amb les que treballeu. Amb això en teniu prou per aquesta setmana.

Si volguéssiu avançar més amb el projecte, hauríeu d'entrenar un classificador (us suggerim un SVM) que generarà un model. Aquest model contindrà tant les etiquetes com els paràmetres del model per cadascuna de les etiquetes. Potser però això és massa feina per aquest lliurament, però si esteu motivats us hi podeu anar posant. El classificador complet us el demanarem de cara al 15 de desembre.
