### ISSUE TITLE
[DUBTE] Build database

### ISSUE THREAD

**Issue by carlesm95** [gdsa-upc/gdsa-suport#16]
Després de passar dues vegades per la funció build_database, haurem de tenir dos .txt diferents, un per les ID de les imatges de training i un altre per les de validation o només un .txt amb les ID de totes les imatges?

**Comment by xavigiro** [comment]
Dos fitxers de text. Un amb els ID de les imatges d'entrenament i un altre amb els IDs de les imatges de validació. Més endavant també l'utilitzateu per fer el mateix amb les imatges de prova (test).
