### ISSUE TITLE
[DUBTE] Rank.py

### ISSUE THREAD

**Issue by cmanso** [gdsa-upc/gdsa-suport#17]
Al script rank.py si ho he entès be, hauriem de crear un fitxer de text per cada imatge que tingui ordenadament, els id de les imatges que més s'assemblin, no?

**Comment by xavigiro** [comment]
Sí correcte... quasi. El fitxer ha de contenir totes les imatges del conjunt d'entrenament, ordenades de més a menys similar a la imatge de consulta.

Les imatges de consulta són, per ara, les imatges del conjunt de validació. Més endavant seran imatges noves estretes del conjunt de prova (test).

**Comment by monicachs** [comment]
Per tant, s'ha de crear un fitxer per cada imatge del conjunt de validació el qual contingui el ranking aleatori del conjunt d'entrenament?
Resumint, el resultat han de ser 180 fitxers txt?

**Comment by xavigiro** [comment]
Ho dius correctament @monicachs... quasi. No totes les imatges del conjunt de validació són consultes, només les que no estan etiquetades amb la classe "desconegut". En concret, com que hi ha 12 edificis i 10 imatges per edifici, en total han de ser 120 fitxers txt.

**Comment by cmanso** [comment]
Doncs, en aquesta funció hauríem de llegir el fitxer annotations.txt original per saber quines ids són consultes i quines no, no? ja que si llegim del diccionari de caracteristíques no sabem a quina categoria pertany cada id.

**Comment by xavigiro** [comment]
Mmmm... Bona observació Carlos. Molt encertada.

Sí, crec que tens raó i que també caldria passar-li l'anotació del conjunt de validació per saber quines imatges cal utilitzar per generar les cerques.

També es podria fer en el moment de l'avaluació, que és el que havíem pensat inicialment. Ara bé, això seria menys eficient perquè estaríeu executant les cerques també per a les imatges de la classe "desconegut", que després no considerarem en l'avaluació.
