### ISSUE TITLE
Rebeu correus o notificacions dels issues d'aquest repositori? 

### ISSUE THREAD

**Issue by amaiasalvador** [gdsa-upc/gdsa-suport#2]
Rebeu correus o notificacions dels issues d'aquest repositori? Si podeu, responeu en aquest mateix issue. Amb un estudiant que respongui ja en tenim prou... Si heu rebut un correu però no podeu respondre aquest issue, envieu-nos un correu a xavier.giro@upc.edu i amaia.salvador@upc.edu

Gràcies !

**Comment by carlesm95** [comment]
Jo no he rebut cap correu ni notificació

**Comment by amaiasalvador** [comment]
Gràcies per la resposta !

@xavigiro, crec que la solució serà utilitzar les mencions als equips. D'aquesta manera tots haurien de rebre notificacions.
