### ISSUE TITLE
[DUBTE] Get local features

### ISSUE THREAD

**Issue by carlesm95** [gdsa-upc/gdsa-suport#21]
La funció get_local_features.py ens ha de retornar en només una passada tots els descriptors de totes les imatges o hi passarem dues vegades, una vegada per les imatges d'entrenament i una altra per les imatges de validació?

**Comment by amaiasalvador** [comment]
Hola Carles,

la funció _get_local_features_ retorna els descriptors locals d'una sola imatge, no de tot un conjunt d'imatges.

Primer hauràs de cridar-la per totes les imatges d'entrenament per poder obtenir tots els descriptors locals i ajuntar-los en una sol numpy array _X_ de dimensions NxD, on N és el número total de descriptors i D la dimensió d'aquests. Amb els descriptors de _X_ haureu d'entrenar el codebook. És important que en aquest pas només feu servir els descriptors de les imatges d'entrenament.

Un cop tingueu el codebook, haureu de tornar a cridar la funció _get_local_features_ per totes les imatges per obtenir els seus descriptors locals per separat i calcular els assignments i els vectors Bag of Words per cada imatge. Aquest pas sí que l'heu de fer tant per les imatges d'entrenament com per les de validació, ja que necessitareu els vectors de les imatges dels dos conjunts per poder-los comparar.

**Comment by carlesm95** [comment]
Llavors la funció train_codebook què és el que ha de fer exactament? Només calcular els clusters i centroides i retornar-los?

**Comment by xavigiro** [comment]
Sí: a l'entrada li passes tots els descriptors del conjunt d'entrenament i el número de paraules que vulgueu pel vocabulari, i a la sortida seran els centroides corresponents a les paraules (codewords) del vocabulari (codebook/vocabulary).
