### ISSUE TITLE
[DUBTE] Build BoW

### ISSUE THREAD

**Issue by carlesm95** [gdsa-upc/gdsa-suport#22]
La funció build_bow ha de retornar els vectors de bag of words de les imatges de train i validació en una sola passada o podem fer que retorni només un vector bag of words per una imatge i després a la funció get_features completa construim els dos diccionaris que ha de retornar?

**Comment by amaiasalvador** [comment]
Hola Carles,

la funció _build_bow_ hauria de retornar el descriptor BoW per una sola imatge. Com dius tu, la idea seria cridar-la per totes les imatges des d'una altra funció (get_features), que és la que genera i guarda els dos diccionaris amb els bow de les imatges d'entrenament i validació.
