### ISSUE TITLE
[Dubte] train codebook

### ISSUE THREAD

**Issue by monicachs** [gdsa-upc/gdsa-suport#25]
A l'hora de fer el train del codebook quin seria, més o menys, el número de centroides que hauriem de calcular per tenir uns resultats més exactes? Gràcies.

**Comment by amaiasalvador** [comment]
Hola Mònica,

De cara a aquesta sessió us vam dir que utilitzéssiu 100 centroides. Probablement no sigui la millor opció, però per ara el que volem és tenir resultats, no els millors resultats. Si aneu bé de temps, podeu provar amb més centroides i segurament els resultats milloraran, encara que l'entrenament del codebook serà més lent. En qualsevol cas, el número òptim de centroides no el sabem (la intuïció és que com més alt millor, però fins a un cert límit), i és una de les coses amb què haureu d'experimentar en les properes setmanes.
