### ISSUE TITLE
problemes bow

### ISSUE THREAD

**Issue by albertbruna** [gdsa-upc/gdsa-suport#29]
Hola, tinc un problema a l'hora de construir el bow de la sessió 5. Desde la funció exctract_features s'ens ha creat el codebook, pero ens surt un error a l'hora de crear el diccionari, posa que és de la funció bow. Diu així: ''index 353 is out of bounds for axis 0 with size 128'', on 'index' es la variable que utilitzem per passar pels assignments.

Alguna idea sobre com solucionar-ho?

Gràcies!

**Comment by amaiasalvador** [comment]
Hola Albert,

L'error que et surt vol dir que estàs intentant accedir a una posició d'un vector, però aquesta posició queda fora del vector (és a dir, que el vector és més petit que l'index). En el teu cas, vols accedir a l'index 353 i el teu vector només té 128 posicions. Revisa que el tamany del vector BoW que inicialitzes i el contingut del vector d'assignments siguin coherents. Si el tamany del teu vocabulari és de 100, el vector BoW hauria de tenir tamany 100, i els valors dels assignments no haurien de passar de 100 en cap cas.
