### ISSUE TITLE
Problemes amb els resultats del Evaluador del Ranking

### ISSUE THREAD

**Issue by GaryKitkat7** [gdsa-upc/gdsa-suport#30]
Estem arreglant l'evaluador del ranking, i ara ja ens funciona correctament quan ho fem amb poques imatges. El nostre problema surt quan hi posem totes les imatges, que ens queden uns percentatges molt baixos, tot i que pensem que es degut que tenim moltes mes imatges a comparar, no aconseguim augmentar els nostres percentatges

**Comment by xavigiro** [comment]
No estic segur quina xifra esteu esperant com a resultat, però el primer pas és millorar els resultats obtinguts amb les cerques aleatòries. El vostre primer objectiu és que el sistema faci coses que no siguin aleatòries. Així doncs, us hem de comparar amb la xifra del sistema aleatori.

Després, em preocupa que parlis de "perecentatge". La vostra mesura de referència, el MAP, no és cap percentatge. És la mitja de les precisions obtingudes considered els resultats considerant diferents K, en concret, prenent com a K les posicions on us apareixen les imatges rellevants per cada cerca.

L'altra cosa que hauríeu de fer és visualitzar els resultats. Tenen sentit ? Si s'equivoca, té sentit que s'equivoqui ? Potser s'equivoca perquè hi ha edificis que visualment s'assemblen ? O perquè surten imatges amb il·luminació o arbres similars ? Mireu els resultats i analitzeu-los, sempre comparant-los amb els de la solució aleatòria.

D'aquesta forma podreu saber si el vostre sistema està resolent cap problema.

**Comment by GaryKitkat7** [comment]
Els résultats que surten tenen bastant sentit, hem mirat algunes imatges i treballa bé. El nostre únic problema es que el MAP esperat es practicament igual que el del sistema aleatori

**Comment by xavigiro** [comment]
Per determinar si teniu algun error al codi o bé si la mesura ja és correcta, utilitzeu el vostre codi d'avaluació per avaluar un cas molt simple que pugueu calcular fàcilment el resultat manualment. Per exemple, només el resultat d'una imatge de consulta i donant-li: (a) un resultat perfecte amb totes les imatges bones al principi, (b) un resultat pèssim amb totes les imatges bones al final i (c) un resultat aleatori. El cas (a) us hauria de donar un 1.0, el (b) un valor pitjor que el de (c). A partir d'aquí crec que detectareu alguna errada.

Tingueu també present de no considerar les imatges de la classe desconeguda a l'hora de calcular el MAP. Aquestes consultes us podrien biaixar cap a un resultat similar al de l'aleatori.
