### ISSUE TITLE
duda con los pesos de desconocidos

### ISSUE THREAD

**Issue by victor-prt** [gdsa-upc/gdsa-suport#31]
Hola,

En clase dijisteis que diéramos menos peso a las fotos que son de la categoría desconocido a la hora de evaluar el ranking, pero no acabo de entender como afecta el peso de los desconocidos en el ranking. Me podríais dar alguna pista?

**Comment by victor-prt** [comment]
Por que en el caso de que una línea del ranking sea de la categoría "desconegut" sería incorrecto que en ese caso la variable k sumara +0.1 en vez de +1? para calcular la precisión?

**Comment by amaiasalvador** [comment]
Hola Víctor,

crec que estàs barrejant dues coses diferents (o potser quan dius rankings vols dir classificador?).

A l'hora de generar i avaluar els rankings, us vam dir que no utilitzéssiu les imatges de la classe _desconegut_ del conjunt de validació com a consultes. Per tant, els seus rankings no s'han d'avaluar (o ni tan sols generar). Això no vol dir però que les imatges de classe _desconegut_ no hagin aparèixer als rankings de les imatges d'altres classes. De fet, han d'aparèixer. En qualsevol cas, a l'hora d'avaluar els rankings, els pesos no entren en joc. Si estàs avaluant el ranking d'una imatge que, per exemple, pertany a la classe _ajuntament_, qualsevol imatge del ranking que no pertanyi a la classe _ajuntament_ penalitza l'Average Precision en la mateixa mesura.

Crec però que potser la teva pregunta també va relacionada amb la tasca d'aquesta setmana, en la qual heu d'entrenar un classificador. Si més no, és l'únic moment on hem introduït en concepte dels pesos per la classe _desconegut_. La idea és que, per entrenar un classificador, és important que les dades d'entrenament estiguin balancejades (és a dir, que totes les classes tinguin _aproximadament_ el mateix número de mostres). En el nostre cas això no es compleix, ja que la classe _desconegut_ té moltes més imatges que la resta. Per arreglar això, us vam proposar dues solucions:

1) Utilitzar només un subconjunt de les imatges de la classe _desconegut_ a l'hora d'entrenar. Si la resta de classes tenen 25 imatges en el conjunt d'entrenament, n'hauríem d'agafar 25 també per la classe _desconegut_. Això vol dir però que estem descartant imatges.

2) La segona opció és utilitzar totes les imatges d'entrenament, però donar menys pes a les imatges de la classe _desconegut_. Això es fa amb el paràmetre _class_weights_ de la classe [svm.SVC](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC) de scikit-learn. De totes maneres, tal i com ja us vam dir a classe, és recomanable que primer opteu per la solució 1), ja que el concepte és més fàcil i també és més fàcil d'implementar.
