### ISSUE TITLE
Classificador

### ISSUE THREAD

**Issue by albertbruna** [gdsa-upc/gdsa-suport#32]
Hola, el fitxer txt resultant del classificador obtenim com a resultat dues columnes (id's, classes).  Tenim el dubte de si les id's que li entrem amb una llista, extreta del diccionari val_features, estan ben relacionats amb les classes despres d'haver fet el .predict. No se si s'entén, vull dir que si estan ben ordenades...
Gràcies!

**Comment by amaiasalvador** [comment]
Hola Albert,

El mètode _predict()_ ha de rebre els BoW de les imatges de validació i retorna les prediccions corresponents. Si la teva matriu amb els BoW de totes les imatges de validació és de 500x100 (on 500 seria el número d'imatges i 100 el número de centroides), a la sortida tindràs 500 prediccions, i la predicció en la posició 0 serà la corresponent a l'element en la posició 0 del BoW. 

En resum, l'ordre l'estableixes tu. Si la matriu BoW l'has obtingut a partir del diccionari _val_features_, el seu ordre vindrà donat per _val_features.keys()_, així que les prediccions que obtinguis es podran relacionar directament amb els noms a _val_features.keys()_.

Vigileu però a l'hora d'avaluar els resultats, ja que sí que podria passar que el vostre fitxer de text amb les IDs de les imatges i les prediccions no segueixi el mateix ordre que el fitxer de les anotacions. Això vol dir que probablement no podreu comparar directament els dos elements en la mateixa posició de les dues llistes. La solució és ordenar les dues llistes seguint el mateix criteri abans de comparar-les. Si teniu més dubtes sobre això, podeu consultar el meu codi d'avaluació disponible al repositori [gdsa-suport](https://github.com/gdsa-upc/gdsa-suport/blob/master/eval_classification.py).
