### ISSUE TITLE
Diversos dubtes

### ISSUE THREAD

**Issue by ariadnana** [gdsa-upc/gdsa-suport#33]
Bon dia,
ens trobem amb 3 dubtes a l'hora de solucionar errors de la sessió 5, dos en Feature_extraction i un amb gitignore.
A Feature_extraction ens surten uns warnings que no ens impedeixen treballar però tenim curiositat per si es poden evitar.
Al final del Feature_extraction quan intentem crear els pickles per guardar els diccionaris ens surt l'error següent:"TypeError: 'dict' object is not callable" i no trobem la forma de solucionar-ho.
Us hem penjat un notebook per poder veure aquests errors.
https://github.com/gdsa-upc/RdE/blob/master/DubtesRdE.ipynb
L'altre dubte que tenim és que a gitignore per mes que posem que ignori el fitxer parametres no ho fa, ho hem provat amb Prametres.py i /Parametres.py, com ho podem fer?
https://github.com/gdsa-upc/RdE/blob/master/.gitignore

**Comment by amaiasalvador** [comment]
Hola Ariadna,

Sobre els warnings que us surten, en concret en teniu dos de diferents:

_DataConversionWarning: Data with input dtype uint8 was converted to float64.
  warnings.warn(msg, DataConversionWarning)_ 

No tinc clar en quin punt del vostre codi apareix aquest warning. Suposo que sortirà d'alguna crida a una funció de scikit-learn que esperi una entrada en float64 i vosaltres li entreu uint8. Podria ser a l'hora d'utilitzar la funció [sklearn.preprocessing.normalize](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html). Com que el vector BoW simplement és un recompte dels assignments d'una imatge, potser l'esteu inicialitzant en uint8, cosa que és comprensible, ja que no tindrem decimals en cap moment. A l'hora de normalitzar però, si que cal convertir-lo a float per poder dividir per la norma i no obtenir valors enters. La solució més pràctica és inicialitzar el BoW directament amb float64. Crec que si l'inicialitzeu com un [numpy.array amb zeros](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.zeros.html) automàticament serà de tipus float.

_DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)_

Molt probablement aquest error us surti també a l'hora de normalitzar amb la funció de scikit-learn. Aquesta funció espera un numpy.array de tamany (n_samples,n_features). Vosaltres la feu servir per normalitzar el BoW d'una sola imatge, per tant el vostre numpy.array hauria de ser de (1,100) en el cas que el vostre codebook fos de 100 centroides. El problema és que probablement teniu un numpy.array de (100,) en comptes de (1,100), i d'aquí surt el warning. Simplement la funció és queixa de que no li heu passat l'entrada de la manera que esperava. Podeu solucionar-ho fent un [reshape](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.reshape.html) abans d'utilitzar aquesta funció.

Quant a l'error, _TypeError: 'dict' object is not callable_, fixeu-vos que feu el següent

``` python
with open(params('arrel_sortida')+'/dictrain.pickle', 'wb') as save_train:
    pickle.dump(dic_train,save_train)
```

`params` és un diccionari, i per accedir a una de les seves entrades heu d'utilitzar [] i no pas (). En resum, hauria de ser `params['arrel_sortida']`.

Quant als problemes amb el gitignore: pot ser que el gitignore s'apliqui només als arxius nous. És a dir, que si teniu arxius .pickle que ja existeixen al vostre repositori no els esborrarà, però no permetrà que se n'afegeixin de nous. És a dir que els fitxers .pickle que ja teniu pujats potser els heu d'esborrar vosaltres.
