### ISSUE TITLE
Dubte amb els pesos del classificador

### ISSUE THREAD

**Issue by cmanso** [gdsa-upc/gdsa-suport#34]
Bon día,
Tinc un problema assignant el pes de la classe desconegut.
He fet un diccionari dic={'desconegut': x}. Si a x li poso 0.16 em diu que cap és desconegut i si li poso 0.17 que totes ho son. He provat a posar més decimals però sempre trobo un límit entre totes o cap.

Gràcies.

**Comment by amaiasalvador** [comment]
Hola Carlos,

El diccionari que estàs creant té entrades per totes les classes? Hauria de ser així. Cada classe hauria de tenir un pes assignat. El que hauries de fer és assignar els pesos de manera proporcional al número de mostres que té cada classe en el conjunt d'entrenament:

`class_weight =  total_n_samples / (n_classes * n_class_samples)`

on `total_n_samples` és el número total d'imatges d'entrenament, `n_classes` és el número de classes de la teva base de dades i `n_class_samples` és el número d'imatges d'entrenament per la classe per la qual vols calcular el pes `class_weight`.

Amb aquesta fórmula, les 12 classes corresponents a edificis de Terrassa tindran totes el mateix pes i la classe _desconegut_ tindrà un pes més baix ja que `n_class_samples` és més gran. Amb aquests pesos t'has de construir un diccionari de la forma:

``` python
dic = {'desconegut': x, 'farmacia_albinyana':x, 'ajuntament': x, ... }
```

i passar-li al [svm.SVC](http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC) de scikit-learn com a paràmetre `class_weight`.

**Comment by cmanso** [comment]
Ho he fet com dius ara i ens surt 1.3846153846153846 per les classes d'edificis i 0.23076923076923078 per desconegut, que és el que ens donava calculant-lo a mà i encara surt que totes les clases són desconegut.

Gràcies un altre cop.

**Comment by albertbruna** [comment]
Hola, fent això i posant el 'kernel'=linear com a resultat em surten 61 imatges de desconegut sobre 180 imatges. Fet això, estaria ben implementat?

Gràcies!

**Comment by xavigiro** [comment]
Hola @albertbruna : crec que el teu dubte no està relacionat amb el dubte inicial. Crec que la teva pregunta seria en la línia de "com puc saber si el meu sistema fa alguna cosa útil ?". Si és així, la resposta és que el sistema fa alguna cosa útil si les mesures d'avaluació que us hem explicat són millors amb el vostre sistema que no pas amb el sistema "aleatori" que vau implementar inicialment. 

Si no et queda clar, inicia una nova discussió, així després serà més fàcil de trobar i discutir. Gràcies :)

**Comment by amaiasalvador** [comment]
Hola Carlos,

Entenc, doncs, que tot i assignant els pesos, el classificador retorna sempre la classe _desconegut_ per totes les imatges de validació. Malgrat que el dubte de l' @albertbruna no està del tot relacionat amb aquest issue, sí que dóna alguna pista de la possible solució. El classificador SVM té molts paràmetres, i triar-ne uns o uns altres pot afectar molt als vostres resultats.

@chiec , entenc que de moment esteu fent servir els paràmetres per defecte del classificador. Com a mínim, jo acabo de fer aquesta prova i obtinc el mateix resultat que tu: el classificador sempre prediu la classe _desconegut_. Ara, si busqueu altres combinacions de paràmetres, el resultat canvia bastant... :)

Per provar molts paràmetres, no cal que ho feu a mà. La classe [GridSearchCV](http://scikit-learn.org/stable/modules/generated/sklearn.grid_search.GridSearchCV.html#sklearn.grid_search.GridSearchCV) ho pot fer per vosaltres si li passeu el llistat de les configuracions de paràmetres que voleu provar. [Aquí](http://scikit-learn.org/stable/auto_examples/model_selection/grid_search_digits.html#example-model-selection-grid-search-digits-py) teniu un exemple de com fer-ho.

**Comment by cmanso** [comment]
Ja ens surt be, moltes gràcies per la resposta.

**Comment by victor-prt** [comment]
Hola Amaia, 

amb la classe GridSearchCV ens diu que els parametres ideals son C = 1 i amb kernel lineal, peró si possem aquests valors al predict no surten del tot bé, en canvi si canviem el valor de C a un número més alt si que dona els resultats correctes. Saps per que podría ser?

**Comment by xavigiro** [comment]
Hola @victor-prt : aquest dubte que planteges no es correspon amb el tema d'aquesta discussió. Pots crear un issue nou per tractar-lo, si us plau ? Gràcies.

**Comment by xavigiro** [comment]
No acabo d'entendre el dubte @victor-prt : com us diu el GridSearchCV que els paràmetres ideals són C=1 i kernel lineal ? Podeu passar-nos un exemple del que us esteu trobant en una notebook ?

**Comment by amaiasalvador** [comment]
Hola,

Crec que el que volen dir és que els paràmetres òptims que troben pel conjunt d'entrenament utilitzant GridSearchCV no són els millors quan els proven en el conjunt de validació. Si és el cas, això simplement vol dir que el teu conjunt de validació o de test no està perfectament representat pel conjunt d'entrenament i no té les mateixes característiques. Per exemple, podria passar que per alguna de les classes no tinguis imatges de nit d'algun dels edificis al conjunt d'entrenament. Llavors el teu classificador aprendrà a classificar molt bé les imatges de dia d'aquell edifici, però quan n'hagi de classificar una de nit s'equivocarà, perquè no n'ha vist mai cap.

En resum, el comportament que descrius és normal i no és preocupant (sempre que la diferència en el resultat no sigui molt gran). Ara bé, seleccionar els paràmetres que millors resultats donin pel conjunt de validació no és bona idea, ja que aquests podrien no ser els òptims per un altre conjunt de dades. Penseu que l'últim dia us donarem un conjunt d'imatges noves (conjunt de test) que el vostre classificador no haurà vist mai. Per això és important que trieu els paràmetres utilitzant el conjunt d'entrenament, d'aquesta manera el vostre classificador serà més robust i genèric.

**Comment by xavigiro** [comment]
Gràcies @amaiasalvador , ara ho entenc millor.
Tal com diu l'Amaia, i he repetit dotzenes de vegades durant el curs, només podeu utilitzar les dades d'entrenament per tal d'entrenar el vostre classificador. Utilitzar les dades amb les que valideu/proveu per optimitzar els paràmetres del vostre classificador induirà a una mala estimació de la qualitat del vostre classificador. A més, en el context d'un petit joc com el que us hem plantejat, això voldria dir fer trampes.

Així doncs, utilitzeu els paràmetres que us doni el conjunt d'entrenament i expliqueu aquesta interessant observació que heu fet en la vostra presentació, així demostreu que heu volgut provar coses noves i anar més enllà, per comprovar el que havíem ja vist a la primera meitat del curs i a la pràctica que vau fer amb el classificador LMS.
