### ISSUE TITLE
feature_extraction útil pel classifier?

### ISSUE THREAD

**Issue by ariadnana** [gdsa-upc/gdsa-suport#35]
Si no he entes malament, al train classifier li han d'entrar els descriptors de les imatges d'entrenament, aleshores el que li entra és la sortida de get_local_features i no de feature_extraction, que treu els BoW, no? Per tant, pot ser que el Feature_extraction que vam fer per l'última sessió no ens serveixi pel classifier?

**Comment by amaiasalvador** [comment]
Hola Ariadna,

Al contrari, sí que us serveix. La part d'extracció de característiques és comuna tant pel classificador com pel ranker. Per entrenar el classificador heu d'utilitzar els BoW de les imatges d'entrenament, que estan emmagatzemats en el diccionari que genereu i guardeu a disc al vostre `Feature_extraction.py` .

**Comment by ariadnana** [comment]
D'acord,  moltes gràcies, ho haviem entès malament.
