### ISSUE TITLE
Dubte amb el resultat del eval_classification

### ISSUE THREAD

**Issue by cmanso** [gdsa-upc/gdsa-suport#36]
El f1-general que ens dóna és pràcticament igual que l'aleatori, és normal? Suposo que més o menys si perquè amb el ranking, qualsevol petita millora ja ajuda, però aquí o classifiques bé la imatge o la classifiques malament, no hi ha punt mig.

**Comment by xavigiro** [comment]
No, no és normal. Vol dir que el vostre classificador no està classificant bé.

Haureu de mirar amb més detall què està passant.
