### ISSUE TITLE
Resultat MAP

### ISSUE THREAD

**Issue by gerardkm94** [gdsa-upc/gdsa-suport#37]
Bones, 

A la classificació final haveu indicat que el nostre MaP és de 0,25, però és una mica més alt, adjunto l'enllaç: https://github.com/gdsa-upc/Egara-View/blob/master/Programaci%C3%B3n/jupyter_sessio_6_2.ipynb

Gràcies.

**Comment by xavigiro** [comment]
Resolt. Gràcies per avisar i felicitats pels resultats.
