### ISSUE TITLE
Problemes amb el log in de la llicencia academica del enthought canopy 

### ISSUE THREAD

**Issue by EricDiCiv5** [gdsa-upc/gdsa-suport#4]
M'ha sorgit ell problema de que quan vull registrarme per aconseguir la llicencia per estudiants del programa em dona errors quan jo li introdueixo el mail i la meva contrasenya per defecte de la upc. És obligatori que em crei un compte de canopy abans o me'he de baixar abans del programar per que desprès funcioni?

Atentament, Eric Díaz.

**Comment by Ivancaminal72** [comment]
Crec que és indiferent crear-te el compte abans o després d'instal·lar-te el programa.

**Comment by EricDiCiv5** [comment]
pot ser pero encara em seugeix donant errors tot i havent-me fet un compte. Seguire investigant

**Comment by EricDiCiv5** [comment]
ja està ivan problema solucionat nomès necesitava activar el compte creat per obtenir la llicència! Moltes gràcies de totes maneres company! ;)
