### ISSUE TITLE
Problemes amb drawmatches

### ISSUE THREAD

**Issue by gerardkm94** [gdsa-upc/gdsa-suport#40]
Buenas,

Tal y como te comenté en clase, seguí intentando solucionar el error y no hay manera, sale el error que dice que no puede llamar al objeto(modulo), incluso intenté calcular los keypoints de nuevo por si ese era el fallo y sigue igual.
(Adjunto jupyter)

https://github.com/gdsa-upc/Egara-View/blob/master/Programaci%C3%B3n/jupyter_sessio5_DRAWMATCHESRANK.ipynb

Tu ves algún error en la implementación?

Gracias!

**Comment by amaiasalvador** [comment]
Hola Gerard,

crec que el problema el tens a l'hora d'importar la funció. Si utilitzes el [meu codi](https://github.com/gdsa-upc/gdsa-suport/blob/master/utils/drawmatches.py), entenc que tens la funció `drawMatches` definida dins d'un script `drawmatches.py`. Llavors, per importar **només** la funció `drawMatches`has de fer:

``` python
from drawmatches import drawMatches
```

D'aquesta manera pots cridar la funció directament: `drawMatches()`.En canvi, si fas:

``` python
import drawmatches
```

estàs important tot el mòdul, i llavors per cridar la funció `drawMatches` d'aquest mòdul hauràs de fer `drawmatches.drawMatches()`. És una mica lio perquè els noms s'assemblen, però és equivalent per altres llibreries, com per exemple `numpy`. Si fas:

``` python
import numpy
```

hauràs d'utilitzar les funcions de numpy fent `numpy.reshape(), numpy.resize() ...`. Però també podries triar les funcions que vols utilitzar i només importar aquestes:

``` python
from numpy import reshape, resize
```

i després les podries fer servir directament, sense posar `numpy` davant..
