### ISSUE TITLE
Jupyter get_features?

### ISSUE THREAD

**Issue by gerardkm94** [gdsa-upc/gdsa-suport#41]
Buenas,

Como requisito en esta entrega, pides que actualicemos la página web con tres demos, una de ellas es el jupyter de Get_features, puedes explicarme para que exactamente? o que tiene que mostrar esta demostración? Tenemos que mostrar el diccionario? O simplemente explicar el código? Ya que esta función no devuelve ningún resultado "Visualmente útil"...

Gracias!

**Comment by amaiasalvador** [comment]
Hola Gerard,

és cert que la notebook d'extracció de característiques no tindrà resultats de classificació o rankings que es puguin avaluar qualitativament. La idea és que expliqueu i executeu el codi que feu servir per fer la extracció de característiques, i que quedi clar què és el que feu en aquesta etapa. Afegiu-hi doncs els detalls de la vostra configuració (per exemple, el número de centroides, tipus de descriptor/s i detector/s, com els combineu si és que ho feu, etc.). Si voleu afegir un resultat més visual, podeu incloure la visualització dels keypoints per alguna imatge. Potser un exemple que us pot servir és la primera part [del notebook](https://github.com/gdsa-upc/gdsa-suport/blob/master/notebooks/gdsa_s5.ipynb) que vaig fer per la sessió 5.
