### ISSUE TITLE
Kaggle: Rank

### ISSUE THREAD

**Issue by JoshuaMolina** [gdsa-upc/gdsa-suport#42]
Estamos intentando subir el archivo que nos genera la función rank, a partir de la función de kaggle, que hay en el repositorio de gdsa-suport, y nos da un error que dice:
"Evaluation Exception: Submission must have 120 rows."
No sabemos porqué da este error,  ya que tenemos 180 líneas y nos piden 120.

A ver si alguien nos puede ayudar.

**Comment by amaiasalvador** [comment]
Recuerda que los rankings de las imágenes de la clase _desconegut_ hay que descartarlos. Hay 180 imágenes de validacion, pero 60 de ellas son de la clase _desconegut_. Por eso te pide 120 líneas.
