### ISSUE TITLE
Perfect accuracy by RdE ?

### ISSUE THREAD

**Issue by xavigiro** [gdsa-upc/gdsa-suport#43]
Dear @gdsa-upc/102-3 ,

we have detected that you have submitted results on the classification task which hit a 1.0 accuracy. While this is possible, its prior probability is low. Could you please double check that you are not submitted the ground truth file instead of your automatic classification ?

Thanks.

**Comment by ariadnana** [comment]
Bon dia, si si, vam tenir l'error que dius, pensàvem escriure'us  aquest mati, com podem borrar aquest resultat?, es que sinó sempre ens sortirà aquest resultat per que és el millor.

**Comment by xavigiro** [comment]
No us dóna l'opció d'esborrar les vostres pròpies submissions des del Kaggle ? Mireu-ho bé i, si realment no podeu, escriviu-nos de nou i mirarem si podem fer-ho nosaltres com a administradors.

**Comment by ariadnana** [comment]
Només podem canviar la descripció, no ens deixa borrar-la

**Comment by xavigiro** [comment]
He llegit que Kaggle no permet esborrar res una vegada s'hagi participat, a menys que ho demanem per correu-e. Ja ho he fet.

El que sí que caldria és que especifiquéssiu a la descripció que aquest valor és erroni.

Igualment, si envieu altres resultats crec que es queden desats i podrem veure'ls l'Amaia i jo, encara que no apareguin a la taula classificatòria pública. Envieu el vostre resultat correcte i proporcioneu una descripció per tal que el puguem identificar.

Tanqueu aquesta incidència una vegada hàgiu enviat el fitxer.

**Comment by ariadnana** [comment]
Gràcies, ja ho hem fet, crec que no podem tancar l'incidència si no som propietaris,
