### ISSUE TITLE
Competició Kaggle

### ISSUE THREAD

**Issue by carlesm95** [gdsa-upc/gdsa-suport#45]
Al Kaggle posa que la competició acaba avui dimarts a les 23:59, encara es poden pujar altres resultats?

**Comment by xavigiro** [comment]
Entenc la confusió i, en aquesta situació, és millor que no en pugeu més. Seria injust per a gent que pensés que el termini era ahir i que per aquest motiu no ha intentat millorar-ho.

Si heu aconseguit fer millores podeu:

(a) Comentar-ho avui a la presentació. Podeu afegir una pàgina addicional especial indicant clarament que el resultat és després del termini.

i/o

(b) Guardeu-vos la millora de cara a la finalíssima amb les dades de prova, que començarà ben aviat.
