### ISSUE TITLE
Llegir train+val

### ISSUE THREAD

**Issue by albertbruna** [gdsa-upc/gdsa-suport#49]
Hola, tinc varios dubtes:
- Com llegir les imatges de 'train' i 'val' juntes per crear el codebook i el diccionari? Ho he provat llegint les imatges d'entrenament i de validació per separat, després juntant els descriptors de les dues i creant el codebook. El mateix amb el diccionari, he anat traient els BoW dels dos per separat i juntant-los en el mateix diccionari (train_val_dic). I per separat el diccionari de les de 'test' (test_dic). 
  Això m'ha creat un codebook del mateix tamany que l'anterior (que no se si ha de ser així) i un diccionari més gran (cosa lògica).
- Podríem copiar i enganxar les imatges de la carpeta TerrassaBuildings900 i juntar val + train? 

Gràcies i bon any!

**Comment by amaiasalvador** [comment]
Hola Albert,

Ja ho fas bé. El codebook és sempre del mateix tamany independentment del número d'imatges d'entrenament que utilitzis. Simplement assegura't que els descriptors que utilitzes són el conjunt de descriptors d'entrenament i de validació (el número de descriptors locals que utilitzes per entrenar el codebook hauria de ser la suma del número de descriptors de cada conjunt). 

A l'hora de guardar els descriptors BoW en diccionaris, et recomano que ho facis per separat (tres diccionaris: train, val, test). Pensa que encara que ara avaluem amb les imatges de test, els rankings han de contenir **només** les imatges del conjunt d'entrenament (és a dir, que els rankings han de ser de longitud 450, igual que abans). Si tens els descriptors de train i de validació junts en el mateix diccionari, et serà més difícil generar els rankings, ja que hauràs de descartar les imatges de validació. Per entrenar el classificador sí que voldràs fer servir els descriptors de train i validació junts, però encara que els tinguis guardats en diccionaris diferents et serà molt fàcil ajuntar-los. En resum, més val guardar-ho tot separat i ajuntar-ho quan faci falta que no pas al revés.

Finalment, i per aquest mateix motiu, jo us recomano que no ajunteu les imatges dels dos conjunts en una sola carpeta: els rankings només han de contenir les imatges d'entrenament, i si aquestes les barregeu amb les de validació després haureu de fer el procés invers per separar-les i generar els rankings. És més pràctic el que ja proposes tu: llegir les imatges per separat i ajuntar els seus descriptors.

Amaia
