### ISSUE TITLE
Dubtes fotografíes

### ISSUE THREAD

**Issue by gerardrosell** [gdsa-upc/gdsa-suport#5]
Tenim el fitxer .zip amb les fotografíes però no sabem com fer-lo arribar... Va bé a través de WEtransfer? Gràcies

**Comment by amaiasalvador** [comment]
WEtransfer va bé, sí.

**Comment by xavigiro** [comment]
Recordeu que l'enllaç al WeTransfer (o on vulgueu) l'haureu d'afegir en la presentació al GDrive.
