### ISSUE TITLE
Metodo alternativo

### ISSUE THREAD

**Issue by gerardkm94** [gdsa-upc/gdsa-suport#50]
Hola,

El sistema que hemos desarrollado para nuestro reconocedor de edificios se basa en la extracción de descriptores para cada imagen mediante la adquisición de sus keypoints, etc.
Este sistema es más eficaz que un sistema basado en descriptores compuestos por energia? como por ejemplo un sistema que forme descriptores basados en las componentes de energia obtenidas mediante DCT o DFT? 

Gracias

**Comment by xavigiro** [comment]
No recordo haver llegit cap article al respecte, així que no puc donar-te cap resposta concloent.

A nivell d'intuició, la resposta seria que no perquè els millors resultats en bases de dades similars al Terrassa Buildings 900 es basen en Bag of Features sobre SIFT, enlloc de descriptors com els que planteges. La meva intuició és que el SIFT és més ric a nivell de descripció de textures i que, a més, el sistema és més eficient perquè es basa sobre un vocabulari après sobre les dades.

Dit tot això: l'experiment que proposes em sembla interessant i el valorarem com un mèrit addicional a l'hora d'avaluar l'últim lliurament que feu. Si feu l'experiment, us proposo que tingueu present també la variable de la mida dels descriptors, és a dir, quant espai ocupen en memòria, o també el temps de càlcul (especialment amb un descriptor basat en la FFT). Aquestes altres dues propietats dels sistemes (més enllà de l'exactitud) també poden servir per argumentar els beneficis d'algunes solucions.

Si us plau pensa en tancar aquest issue si les explicacions t'han semblat suficients.
