### ISSUE TITLE
Adquisición de imagenes

### ISSUE THREAD

**Issue by gerardkm94** [gdsa-upc/gdsa-suport#51]
Buenas,

En el supuesto caso que decidamos optimizar nuestras imagenes de la base de datos para que el sistema obtenga mejores resultados, podemos aplicar estas mejoras también las imágenes de test?
En teoría es un proceso automatizado que podemos aplicar tanto a las de entrenamiento como las de test para optimizar estas imágenes, un pre-procesado.

Gracias.

**Comment by amaiasalvador** [comment]
Hola Gerard,

Entenc que et refereixes a modificar els valors dels píxels de les imatges d'alguna manera de forma automàtica. Si és el cas, aquest procediment cal que l'apliqueu **sempre a totes les imatges que utilitzeu**. Si només ho apliqueu a les imatges d'entrenament estareu forçant diferències entre les imatges d'entrenament i test, que es traduiran en diferències en els seus descriptors visuals i conseqüentment empitjorarà els resultats.

**Comment by xavigiro** [comment]
Un dubte per assegurar-me que no tenim cap problema: quan dius que "optimitzeu" les images de la base de dades NO vol dir que n'afegiu de noves, oi ? Esteu sempre treballant només amb el conjunt de dades incloses en el [Terrassa Buildings 900](https://imatge.upc.edu/web/resources/terrassa-buildings-900), correcte ?

**Comment by gerardkm94** [comment]
Correcte, simplement estem aplicant a les imatges un pre-processat amb matlab, per corregir angles de desviació a l'hora de fer la foto, de manera que les fotos del mateix edifici quedin el més semblant possible i sigui més fàcil trobar els kpoints, però sempre a TerrassaBuildings900.
