### ISSUE TITLE
[ENTREGUES] Examen 13 de Gener de 2016

### ISSUE THREAD

**Issue by amaiasalvador** [gdsa-upc/gdsa-suport#52]
En [aquest link](https://docs.google.com/presentation/d/1ewJdmalW5P4I4qrGhOh2-MdHenHQQ704jlMedljOvgY/edit?usp=sharing) trobareu les diapositives de la sessió del 22 de Desembre de 2015.

De cara a l'entrega abans de l'examen, responeu aquest issue (abans del termini) amb el nom del vostre equip i l'enllaç públic a la presentació a Google Drive.

**Comment by Christiancuz** [comment]
Search-Around https://docs.google.com/presentation/d/13xU29aSd_dUi7onPu6UjdJAxxMqR2AXorLx8SrR1jb0/edit#slide=id.gfc24b2036_0_62

**Comment by FcoOrtiz** [comment]
Building Recognizer https://docs.google.com/presentation/d/1YQfYF4gc58sjcJw30Vvzua51img29PkmFbRz13Y8ECU/edit?usp=sharing

**Comment by AZarzuela** [comment]
Egara-View
https://docs.google.com/presentation/d/1exgEO5AZCWiu52LrPAqg3ub6_E--gODIT8JSJv9Uns0/edit?usp=sharing

**Comment by Christiancuz** [comment]
Search-Around 
https://docs.google.com/presentation/d/13xU29aSd_dUi7onPu6UjdJAxxMqR2AXorLx8SrR1jb0/edit

**Comment by sergisantana** [comment]
What a building App!
https://docs.google.com/presentation/d/1XK3Jdc_td4F4XCzGln555MiI-nxEq2yqkQbPrAw7ai4/edit?usp=sharing

**Comment by xavigiro** [comment]
Els equips @gdsa-upc/101-3 Discover Terrassa i @gdsa-upc/102-3 RdE no heu enviat els vostres informes finals dins de termini. Per quin motiu ? Podeu enviar-lo urgentment ?

**Comment by sadek4** [comment]
RdE 

https://docs.google.com/presentation/d/1QuUlWTtAQsDWcAhzmGKd1ATcsVwCeTXPqg8K_nacvh0/edit?usp=sharing

**Comment by anapiernas** [comment]
Discover Terrassa
No sabíem que teniem que entregar una presentació. Aquí la deixem. Sentim molt el retràs.

https://docs.google.com/presentation/d/1xR12IsWil6WWoX7EipEKdheMu6l8gtgOnElR8Wav9do/edit?ts=56960d0c#slide=id.p

**Comment by amaiasalvador** [comment]
Equips @gdsa-upc/101-3 Discover Terrassa i @gdsa-upc/101-1  What a building App ! : Feu les vostres presentacions públiques !

**Comment by anapiernas** [comment]
Ja está

https://docs.google.com/presentation/d/1xR12IsWil6WWoX7EipEKdheMu6l8gtgOnElR8Wav9do/edit?usp=sharing
