### ISSUE TITLE
Per què no ens apareix al Private Leaderboard la millor submission d'Egara View ?

### ISSUE THREAD

**Issue by xavigiro** [gdsa-upc/gdsa-suport#53]
Amb @amaiasalvador hem observat que l'equip @gdsa-upc/102-2 té un resultat molt bo en classificaicó que no ens està apareixent al "Private Leaderboard" que nosaltres sí que podem veure. Aquest resultat va ser enviat a la matinada de dilluns a dimarts (em surt a les 4 de la matinada, no sé si és l'hora correcta...).

No estem segur sobre quin és el motiu perquè també som novells amb el Kaggle :)

Tinc algunes hipòtesis relacionades amb el següent punt de la normativa:

> Submission Limits
> You may submit a maximum of 2 entries per day.
> You may select up to 2 final submissions for judging.

Tinc tres hipòtesis:

(a) La primera hipòtesi és que aquest darrer enviament va ser el tercer d'un període de 24 hores, amb el que va quedar invalidat. Si aquesta hipòtesi fos bona, quedaria resolt enviant el resultat de nou. El sentit comú però em fa pensar que quan parlen de "days" no parlen de períodes de 24 hores sinó de dies naturals.

(b) La segona hipòtesi és que el Leaderboard només es refresca a mitjanit. Si és així, ja apareixeria el resultat quan es tanqui la competició a la 1 de la matinada (ens vam equivocar amb la zona horària...). Aquesta hipòtesi és una mica estranya, però a banda del Leaderboard numèric també veiem una gràfica i a allà sí que hi apareix aquest nou resultat. Estic força desconcertat...

(c) La tercera hipòtesi té a veure amb el punt de "select up to 2 final submissions" for judging. Això voldria dir que d'alguna forma els equips esteu seleccionant les submissions que s'avaluen, i podria ser que aquesta submission no estigués seleccionada. Aquesta hipòtesi l'hauríeu de comprovar els propis equips perquè l'Amaia i jo no ho podem veure.

Us mireu, especialment, la hipòtesi (c) ? A priori és la que em sembla la més raonable.

**Comment by carlesm95** [comment]
Sobre la hipòtesi (a) vaig veure que ahir dilluns a la nit em deixaba fer un enviament i que a partir de les 00 en podia fer dos més.
Per altra banda, no se suposa que el kaggle ja t'agafa el millor resultat? Si no és així que fem, escollim dos del ranking i uns altres dos del classificador aleatoriament? Perquè nosaltres no veiem cap resultat.

**Comment by xavigiro** [comment]
Hola @carlesm95 ,

pel que dius a la teva resposta sembla que efectivament podeu escollir quins dos enviaments voleu que siguin els que comptin ? Teniu aquesta possibilitat ?

La resposta formal a la teva pregunta és que hauries d'escollir els enviaments que es corresponen a la configuració que us proporcioni millors resultats amb la parella entrenament+validació.

Pels comentaris i descripcions que heu fet en els enviaments entenc que els vostres darrers enviaments en les dues competicions són els que creieu que funcionen millor. Així doncs, hauríeu de seleccionar aquests dos. En cas contrari, tinc la sensació que el Kaggle selecciona per defecte els dos primers.

En concret, haurien de ser les que tenen les següents marques temporals:
Retrieval > Tue, 12 Jan 2016 04:03:08
Classification > Tue, 12 Jan 2016 04:00:00 

Veieu la forma de seleccionar-ho ?

**Comment by carlesm95** [comment]
Creiem que sí, ara mateix hem seleccionat 2 resultats. Els podeu veure ara?

**Comment by xavigiro** [comment]
Sí, ara ja estan els vostres millors resultats al leaderboard. Crec que quan es tanqui la competició també podreu veure vosaltres el private leaderboard.

Sort !
