### ISSUE TITLE
Millor puntuació a kaggle de la que posa a Leaderboard

### ISSUE THREAD

**Issue by albertbruna** [gdsa-upc/gdsa-suport#54]
Hola, he vist que a Leaderboard de la part de classificació ens surt una puntuació de 0.74074, però mirant a 'My submissions' veig que la millor és la de "Sun, 10 Jan 2016 20:43:57" que dóna 0.77407.

Suposo que deu ser pel mateix problema que plantegaves abans amb Egara-View...

Gràcies.

**Comment by xavigiro** [comment]
Hola @albertbruna ,

tens tota la raó. Vaig fer una repassada per tots els equips però se'm va passar el vostre cas. Em sap greu.

De cara a la qualificació final tindrem en compte la vostra millor submission de 0.77407, però no podem canviar els resultats del Kaggle. Em sap greu.

**Comment by albertbruna** [comment]
Cap problema @xavigiro si ho teniu present ja és suficient.:)
