### ISSUE TITLE
Problemes en l'apartat d'evaluacio del ranking

### ISSUE THREAD

**Issue by yanguas39** [gdsa-upc/gdsa-suport#56]
Hola Amaia,
Tinc un problema en l'apartat d'evaluació del ranking, just en la sentencia: 
"i_class = list(annotation_train.loc[annotation_train['ImageID'] == i]['ClassID'])[0]", en la funció get_hitandmiss. El error que em dona és "IndexError: list index out of range ". He comprovat la longitud de la llista ranking i és de 451. Pero em dona el error, quan intenta accedir en la posicio 277.
![error_get_hitandmiss](https://cloud.githubusercontent.com/assets/23135017/21137399/acb2893a-c129-11e6-8225-522c78272a93.jpg)

**Comment by xavigiro** [comment]
En aquesta ordre hi ha dues accessos: a ClassId i a ImageId. Podríeu partir la funció en dues línies separades per aclarir quin dels dos accessos us està fallant ? Em fa por que l'ImageId que demaneu no hi sigui i que sigui aquell que us estigui donant l'error.

Alguna altra idea @amaiasalvador ?

**Comment by yanguas39** [comment]
Pel que he vist el error és de ClassId. Pero ara en comptes de fallar en el numero 277 de la llista, ho fa en el 361.
![error_get_hitandmiss2](https://cloud.githubusercontent.com/assets/23135017/21144388/bc2ed6ae-c14a-11e6-8596-a8db853408f4.jpg)

**Comment by xavigiro** [comment]
Interpreto el codi de forma diferent.

El que estàs llegint és un llistat d'imatges anotades. La x ha de correspondre a l'ID de la imatge, i a la línia 99 el que fas és llegir l'ID de la classe associat a aquella imatge.

El dubte doncs que em sorgeix és si l'ID de la imatge (la x) a la que intentes accedir existeix. En concret, podria ser que al llistat de ranking hi hagi identificadors d'imatge que no estiguin al conjunt d'imatges anotades ? Comprova-ho manualment mirant el fitxer d'anotacions que li dones i que teòricament pots llegir.

**Comment by amaiasalvador** [comment]
Jo diria que el que et dóna problemes és l'accés a la primera posició de la llista amb [0], ja que l'error és  ```list index out of range```, i ```annotation_train``` no és una llista:

``` python
i_class = list(annotation_train.loc[x]['ClassID'])[0]
```  

Si ho divideixes en dos passos podràs veure el que falla exactament:

 ``` python
i_class = list(annotation_train.loc[x]['ClassID'])
print len(i_class)
i_class = i_class[0]
```

**Comment by yanguas39** [comment]
Probant això em surt que la longitud de i_class es 0 en el moment de l'error. Per tant entenc que el problema està en la linea` i_class = list(annotation_train.loc[x]['ClassID'])`, que no s'ejecuta bé.

**Comment by yanguas39** [comment]
Ja funciona tenia un problema amb l'anotació d'imatges de la BBDD hi havia una que estava anotada amb l'ID 29796-14601-23662(1) <- el (1) era el problema.
