### ISSUE TITLE
Problemes en el get_features

### ISSUE THREAD

**Issue by viscarri13** [gdsa-upc/gdsa-suport#57]
Hola, ara hem fet corre el codi en el meu ordinador i ens ha sortit un error que previament ja ens havia donat el error a l'ordinador de l'Albert yanguas. El que passa es que en el seu hem fet un restart del kernel i llavors ha funcionat, però en el meu no hi ha manera
<img width="1280" alt="captura de pantalla 2016-12-13 a las 18 08 56" src="https://cloud.githubusercontent.com/assets/23341700/21150439/3eefa46a-c15f-11e6-918d-5daf2b21d657.png">

**Comment by amaiasalvador** [comment]
Té pinta de que la imatge no s'ha carregat i per això no podeu accedir a l'atribut ```shape```. Reviseu la part del codi on carregueu la imatge de disc.
