### ISSUE TITLE
Error: This MiniBatchKMeans instance is not fitted yet.

### ISSUE THREAD

**Issue by yanguas39** [gdsa-upc/gdsa-suport#58]
Estic intentant fer una combinació del BoW amb SIFT i el BoW amb ORB, concatenantlos. De tal manera que calculo dos detectors i extractors, un per ORB i un per SIFT. Extrec els descriptors per cada imatge amb cada un dels extractors. Faig dos KMeans un per ORB i un per SIFT. I finalment extrec els descriptors BoW els concateno.
Quan intento fer els assignaments per en el KMeans del ORB em salta aquest error: `
NotFittedError: This MiniBatchKMeans instance is not fitted yet. Call 'fit' with appropriate arguments before using this method. `

Salta quan intenta ejecutar `assignments = km.predict(descriptors)`

![error_features_combination_late](https://cloud.githubusercontent.com/assets/23135017/21270468/17309fb0-c3b7-11e6-833c-dc510383cf6c.jpg)

**Comment by amaiasalvador** [comment]
L'error t'està dient que la instància de kmeans  ```km``` que li passes a la funció encara no té els centroides computats (falta cridar el mètode ```fit``` amb els descriptors del conjunt d'entrenament). Potser ja ho has fet, però no estàs carregant bé la instància un cop cridat el mètode ```fit``` (és possible que estiguis inicialitzant el kmeans de nou enlloc de carregar el que ja havies entrenat?). Si no és això, podries indicar-nos on tens el codi on crides la funció ```get_assignments```?
