### ISSUE TITLE
PRESENTACIÓ 22-DEC-2016- TEAM1

### ISSUE THREAD

**Issue by Mmarta19** [gdsa-upc/gdsa-suport#59]
https://docs.google.com/presentation/d/1fKgvZxy72OWYSbQwmD-X3raqaJ12RukCvyqcI8aD8mo/edit#slide=id.g1a34d18ab0_0_135

**Comment by xavigiro** [comment]
GENERAL

DAVID
- Una mica estrany l'ús dels temps verbals en el teu discurs: "amb aquest primer resultat no estem molt contents". Hauria de ser "no vam estar molt contents".
- Falta assajar més.

MARTA C
- Molt bé.

MARTA B
- Molt bé.
