### ISSUE TITLE
Presentació 22 de Desembre- Equip3 (BauID)

### ISSUE THREAD

**Issue by lauraigdi** [gdsa-upc/gdsa-suport#60]
https://drive.google.com/open?id=1llOCeLkuYzMO_Ydx1BFGB3MYuJZZm88E8oCrgKRxmBk

**Comment by xavigiro** [comment]
GENERAL
- Mostrar imatges per argumentar els punts de vista.
- Gràfics de MAP vs codebook
- L'anotació amb metades s'hauria d'haver explicat diferen (i geolocalització ?).
- Manquen elements gràfics per explicar els conceptes que heu anat descrivint (metadades, particions...).
- Haguéssiu pogut fer el canvi entre train i validació.

LAURA
-

JOAN
- Bona dicció.

RUBEN
- No miris tan a la pantalla.

**Comment by xavigiro** [comment]
La vostra presentació final:

https://drive.google.com/open?id=1HswU-TBnl6trYbVsvESLAGzJegoxyqfLXsyHphNX81w

**Comment by xavigiro** [comment]
GENERAL

- Previ: 0.269 amb SIFT-1024
- Han provat diferents particions de les dades. Amb les gràfiques que han generat costa veure les diferències.
- DOnat resultats amb la partició que ha donat millor MAP.
- Han estudiat la desviació estàndard.
- No han sabut aleatoritzar les mostres.

LAURA
- Bona dicció i explicació.

RUBÉN
- Ben explicat però ha faltat seguretat. Potser es podria assajar més ?

JOAN
- Bona dicció, sembla que sigui qui conegui millor el tema.
