### ISSUE TITLE
Presentació 22 Desembre grup 5

### ISSUE THREAD

**Issue by viscarri13** [gdsa-upc/gdsa-suport#61]
https://drive.google.com/open?id=1c2XeNBm0gpzU-S7iC1_9_-JwcxlA5O1swSBqup6b5DM

**Comment by xavigiro** [comment]
GENERAL
- Molt bé el disseny gràfic i ús de recursos visuals.
- Bé de temps (8 minuts).
- Numereu les pàgines de la presentació.
- Mostreu els resultats de la mida de codebook en una gràfica lineal.
- Mostreu imatges dels millors i pitjors resultats per argumentar quins van millorar i pitjor.
- Hauríeu d'haver assejat més abans.
- Bona dicció els dos.
- En Joan té tendència a trepitjar a l'Albert, especialment en el torn de preguntes i respostes.

JOAN
- Intenta no mirar tan a la pantalla.

ALBERT
- Acosta't davant la pantalla. POdríeu haver intercanviat llocs.
