### ISSUE TITLE
Presentació 22 Desembre - Enjoy Exploring Terrassa

### ISSUE THREAD

**Issue by kikevite** [gdsa-upc/gdsa-suport#62]
https://docs.google.com/presentation/d/1Ol8B8NNOnoMb-ZDMElMFij1bH5sTInz8Qd3Y1cDpm_4/edit#slide=id.g1a3455afc3_0_0

**Comment by xavigiro** [comment]
GENERAL
p.4: Gràfica de línia enlloc de barres !!
Per què no heu mirat entre 4k i 8k ?!
Bon ús d'elements gràfics
Per què el cel taronja ?
Càlcul de MAP en imatges de dia o de nit / girats i no girats ?
Podríeu un estudi per veure quins edificis es confonen més entre ells.
La part de resultats qualitatius s'ha fet una mica massa llarga.
Estructura general de la presentació confusa. Primers tots qualitatius i després tots quantitatius. Caldria haver anat més per blocs i cobrir-lo tot.
Falta una conclusió final.

BERNAT
- No tenies el dia més fluït. Crec que pots millorar-ho assajant.

CRISTINA
- Molt bé.

ADRIÀ

RICARD
- Molt bé.
