### ISSUE TITLE
Presentació equip 4

### ISSUE THREAD

**Issue by serginavarro** [gdsa-upc/gdsa-suport#63]
[Presentació](https://drive.google.com/open?id=1kPW7dIn1MHWKluWvtV3_aR2NJTlmm2-AdDa4cySGnJ0)

**Comment by serginavarro** [comment]
@xavigiro

**Comment by xavigiro** [comment]
GENERAL
- La 3a samarreta ?
- Podeu fer pantalla completa amb el GDrive.
- Bona visualització del resultats per categoria amb el MAP.

SERGIO
- Fas un lleuger balanceig amb el cos que pots mirar d'evitar.

ADRIÀ
- Bé.

PABLO
- Bé.
