### ISSUE TITLE
Error per falta d'annotation.txt a la carpeta val

### ISSUE THREAD

**Issue by adriamarquez** [gdsa-upc/gdsa-suport#64]
Ens dóna l'error perquè no existeix l'annotation.txt dins de la base de dades a les imatges de val.

**Comment by amaiasalvador** [comment]
Hola Adrià,

efectivament, no hi ha anotacions pel conjunt de validació. Això simplement vol dir que no podreu avaluar els resultats vosaltres mateixos. Heu de generar els rankings per val i test i pujar-los a la competició de Kaggle amb el format correcte per obtenir el mAP.

**Comment by serginavarro** [comment]
Com es fa per poder pujar-lo al kaggle?

**Comment by amaiasalvador** [comment]
Llegiu les instruccions de [la competició](https://inclass.kaggle.com/c/terrassa-buildings-2016/). a les seccions Description, Evaluation i Data trobareu la informació que necessiteu i un fitxer ranking d'exemple.
