### ISSUE TITLE
Error a cv2.cvtColor

### ISSUE THREAD

**Issue by ghost** [gdsa-upc/gdsa-suport#65]
Ens dóna un error ( error (-215 ) scn==3 || scn==4 ) a l'eval_rankings quan utilitza la funció cv2.cvtColor. 
Hem buscat a internet , però les solucions que donen no arreglen res.

**Comment by amaiasalvador** [comment]
Quines solucions? Amb la informació que doneu crec que no us puc ajudar gaire... Seguint les recomanacions que donen [aquí](http://stackoverflow.com/questions/30506126/open-cv-error-215-scn-3-scn-4-in-function-cvtcolor), us diria que mireu que estigueu llegint bé les imatges abans de fer la crida a ```cv2.cvtColor```
