### ISSUE TITLE
Upload a submit

### ISSUE THREAD

**Issue by yanguas39** [gdsa-upc/gdsa-suport#66]
He penjat el archiu amb el format adecuat. Jo he entes que a la columna querys hi van les ids de les imatges de train, seguit del ranking, que es composa de les imatges de train + val. A l'hora de penjar em diu que no pot trobar en la columna query unes ids que es corresponen a les imatges de validació.

**Comment by yanguas39** [comment]
El archiu que intento penjar es en el kaggel per fer l'evaluacio del ranking.

**Comment by amaiasalvador** [comment]
Hola,

les queries són les imatges de val i test, i els rankings per cadascuna d'elles han de ser només de les imatges de train. La base de dades que heu d'utilitzar és la que trobareu a la secció Data de la competició a Kaggle, i no pas la base de dades antiga que heu utilitzat fins ara.

**Comment by yanguas39** [comment]
Pero llavors no hi han 895 files, sino que n'hi han 1260, no?

**Comment by yanguas39** [comment]
Ara no em dona error de que falten queris pero clar el archiu te 1252 columnes, que jo entenc que son les imatges tan de train(900)+val(360), i em salta l'error que l'archiu ha de ser de 895 files, que es el que tenia quan nomes evaluava per train.

**Comment by amaiasalvador** [comment]
Ha de tenir tantes files com queries (imatges de val + test juntes) i tantes columnes com imatges de train, que són les que han d'aparèixer al ranking. Podeu mirar el fitxer d'exemple que hi ha a la competició com a referència.

**Comment by yanguas39** [comment]
Clar pero el fitxer d'exemple te 895 files que son les que demana el kaggle, pero quan genero el fitxer amb 895 files nomes hi han les imatge de test. Quan afageixo les imatges de val el fitxer te 1252 files. I si penjo el archiu de 895 files em diu que falten les imatges de val, com es d'esperar. I quan intento penjar el de 1252 files el kaggel em diu que nomes poden ser 895.

**Comment by yanguas39** [comment]
Ja he vist el error, estava fent els queris amb les imatges de train i no de test.

**Comment by xavigiro** [comment]
Està resolt el dubte ? En aquest cas hauries de tancar la incidència @yanguas39 . Gràcies !
