### ISSUE TITLE
Problemes Kaggle

### ISSUE THREAD

**Issue by yanguas39** [gdsa-upc/gdsa-suport#67]
Hola,

Al penjar el archiu al Kaggel s'ha penjat dues vegades, hi ara no em deixa fer més probes.

**Comment by amaiasalvador** [comment]
Hola,
hi ha un límit de 2 fitxers al dia. Si ja no us deixa haureu d'esperar a demà... Si considereu que és molt urgent us podeu inscriure a la competició amb un altre usuari i començar de nou.
