### ISSUE TITLE
RANSAC

### ISSUE THREAD

**Issue by yanguas39** [gdsa-upc/gdsa-suport#68]
Hola,

M'agradaria probar de implementar l'algoritma de RANSAC, he estat miran informació de com fer-ho, el primer pas es seleccionar un grup de punts aleatoris, pero no entenc d'on s'han d'agafar aquets punts.

**Comment by MartaCollPol** [comment]
Jo també ho he estat mirant, hi ha un exemple a l'opencv que utilitzen els keypoints del SIFT com a punts, després utilitza una funció de match que en teoria busca els punts de la imatge query en la imatge de train i crea una llista amb els punts trobats ordenada segons la distància de menys a més del punt original de la query respecte al "mateix" punt trobat en la de train, després amb els 10 primers resultats de la llista "en teoria els millors, de menys distància" aplica ransac per descartar falsos matches, o aixó és el que he entés jo. A mi m'ha donat problemes amb la meva versió de l'opencv, pots probar si a tu et funciona. Aqui tens l'exemple, http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_feature2d/py_feature_homography/py_feature_homography.html
