### ISSUE TITLE
Pressentació 23-Gener-2017 TEAM1

### ISSUE THREAD

**Issue by Mmarta19** [gdsa-upc/gdsa-suport#69]
https://docs.google.com/presentation/d/1IB9tSpWoAGeoOvT0OztR9OXLKhyieYwC6vBZLGcT80M/edit#slide=id.p

**Comment by xavigiro** [comment]
GENERAL
- Van provar early fusion vs rootSIFT.
- Van pujar fins a 11,000.
- Van canviar de RGB a grayscale per acabar de guanyar.
- Van porvar Keras i TF però sense èxit.
- Van executar un codi de DLCV però no el van saber adaptar a la nova base de dades.
- Van provar agglomerative clustering.
- Han ajudat a altres equips (diverses mencions d'agraïments).
- Van mirar també els descriptors HOGs.
- Amazon Web Services, però tampoc es van 

MARTA B.
- Ben explicat.

DAVID
- Ben explicat.

MARTA C.
- Molt ben explicat, amb un alt nivell tècnic també.
