### ISSUE TITLE
Presentació 23 Gener 2017 TEAM 5

### ISSUE THREAD

**Issue by viscarri13** [gdsa-upc/gdsa-suport#70]
https://docs.google.com/presentation/d/18kr2XXsRIafx4p6P7Xvl7GBZ95zi2hO4F60qs28oqy4/edit?usp=sharing

**Comment by xavigiro** [comment]
GENERAL
- Com a novetat han mirat de millorar amb el TF-IDF perquè en la versió anterior no funcionava gaire bé. Van implementar el TF-IDF de nou, però tampoc li ha millorat els resultats.
- Van intentar fer funcionar el RANSAC, però tampoc se'n van sortir. La Marta Coll el va ajudar per resoldre-ho.
- Nou logo.

JOAN
- Crec que ha faltat una mica d'assaig. Saps el que vols dir però ha semblat que improvitzaves una mica.

ALBERT
- Ben explicat, malgrat que no hagi funcionat.
