### ISSUE TITLE
Presentació 23 Gener 2017 Equip2

### ISSUE THREAD

**Issue by kikevite** [gdsa-upc/gdsa-suport#71]
https://docs.google.com/presentation/d/1tAGuff363eBT5GbqVj1YCMlYcIp9q2Xxw9rUffX-exU/edit?usp=sharing

**Comment by xavigiro** [comment]
MILLORES
- Agraïments a l'equip 1 per l'ajuda donada.
- Van veure que estaven utilitzant el RootSIFT enlloc del SIFT.
- Van executar el Canopy amb la GPU que els hi va permetre treballar amb vocabularis visuals més grans.
- Proves amb diferents tipus de clustering.
- Van provar de codificar les dades amb sparse, però no ho van saber córrer.
- Filtres de Sobel.
- Canvis en filtratge de la imatge... però no ho van implementar.
- Van pensar en fer cerques locals... però no ho van implementar tampoc.
- La web ha estat millorada i ha quedat molt bé.

BERNAT
- Alguns moments en blanc. No estava del tot assajat i preparat.

CRISTINA
- Molt bona dicció i comunciació oral. 

RICARD
- Et vas tocant les mànigues i el rellotge.
- Mira de vocalitzar una mica més.

ADRIÀ
