### ISSUE TITLE
LLiurament de les tasques per la setmana 3

### ISSUE THREAD

**Issue by xavigiro** [gdsa-upc/gdsa-suport#74]
Responeu a aquest missatge amb una resposta que tingui com a títol el vostre identificador d'Equip (Equip X). Podeu mirar el resum dels [lliuraments de 2016](https://docs.google.com/presentation/d/15D5ueIcXWkR9IZmZPlSNVCkjCXeH_aYLzpqoo92mv0o/edit?usp=sharing) per anticipar-vos a errors comuns.

**Comment by mariahuto** [comment]
Equip 6

**Comment by Daniel-dMialdea** [comment]
Equip 2
https://docs.google.com/presentation/d/1NLqrmjugQptpCZcIjHgNPGC6k7wWzvEBud_B-qvFP2Q/edit?usp=sharing

**Comment by lgotarra** [comment]
Equip 4
La presentació es troba al següent [enllaç](https://docs.google.com/presentation/d/1wzgHHAdPmBkz0yibbY3jWujlIzdMaDF1VwzPPanJ0zk/edit)

**Comment by vpachecogarcia** [comment]
Equip 5:

[Presentació](https://docs.google.com/presentation/d/1LW8pFQoSjwM9wL5X-YFIhWHqg_rriLiLeP1GUBp_UXc/edit?usp=sharing)

**Comment by xavigiro** [comment]
Comentaris pels equips que heu lliurat tard:

EQUIP 4

- no heu afegit enllaços cap als vostres scripts i notebooks per tal que els pugui veure directament sobre el repo de github

EQUIP 5
- proporcioneu més evidències del resultat de les vostres tasques.
- milloreu la comunicació gràfica amb les presentacions. Aprofiteu els recursos visuals.
