### ISSUE TITLE
Lliurament de les tasques per la sessió 4

### ISSUE THREAD

**Issue by xavigiro** [gdsa-upc/gdsa-suport#79]
Editeu [aquesta presentació](https://docs.google.com/presentation/d/1p7CA3PKtyVs0K1IEH5iSpapAIx6tgQBYzsGxFyjOAFU/edit?usp=sharing) per tal d'informar del resultat de les vostres tasques de cara a la sessió 4.

Fixeu-vos que hi ha una modificació respecte l'indicat a classe, ja que no es demana per aquesta sessió una avaluació dels resultats. Aquesta tasca queda post-posada per la sessió 5. La rúbrica ha estat actualitzada per tal de reflexar aquests canvis.

**Comment by rogertorresric** [comment]
Aquest és l'enllaç de la presentació que vam fer l'equip 6: https://drive.google.com/open?id=1OOfe_bFY_epn2nK-wxdb8GBJtp0GgSgNVOVjQENFaG8.
