### ISSUE TITLE
Dubte fotografies

### ISSUE THREAD

**Issue by AlbertAltarriba** [gdsa-upc/gdsa-suport#8]
Bon dia, tenim un petit dubte en quant a les fotografies a entregar. Un dels nostres edificis és el museu de la ciència de Terrassa i no ens queda clar si hem de fotografiar la façana principal de l'edifici 
​que és la més reconeguda/emblemàtica o bé la façana de l'entrada principal del museu.
Gràcies per la vostra atenció.

Façana principal: [link](http://www.sugeralia.com/wp-content/uploads/2015/01/144-01.jpg?aec106)
Façana entrada principal: [link](http://esphoto980x880noname.mnstatic.com/b0bca5b67b9b59228a1716418a52e9de)

**Comment by amaiasalvador** [comment]
Hola Albert,

copio aqui el que t'he contestat per correu fa una estona, per poder deixar l'issue tancat.

_Hola Albert,_

_nosaltres teníem en ment l'edifici de la primera imatge. Prepareu doncs les 50 imatges només d'aquest edifici. De tota manera, si ja heu recopilat fotos de la façana de l'entrada principal, envieu-nos-les també, ja que potser les acabem afegint a la base de dades._
