### ISSUE TITLE
Team 2 (K-LERA) error en jupyternotebook

### ISSUE THREAD

**Issue by irenenus** [gdsa-upc/gdsa-suport#80]
Todas las funciones por separado nos funcionan pero al arrancarlas des del script general cuando entrenamos el train_codebook con el comando km.fit(X) nos da un error: 
ValueError: setting and array element with a sequence.

**Comment by lgotarra** [comment]
Buenas! Tal vez sería de ayuda que colgarais algún link de dicho notebook. 

Aún así, este error se refiere a que teneis algún input (una lista, por ejemplo) que no puede ser "redimensionada" a una matriz. Puede ser que haya algún objeto o parámetro con distintas posibles longitudes.

Reitero, sin el código es difícil sacar algo en claro

**Comment by irenenus** [comment]
Sí por lo que habíamos encontrado el problema es de dimensiones de la matriz pero no sabemos encontrar el error

Adjunto los scripts
[Get_features](https://github.com/gdsa-upc/K-LERA/blob/master/Semana4/get_features.py)
[script1](https://github.com/gdsa-upc/K-LERA/blob/master/Semana4/script1.py)

Merci
