### ISSUE TITLE
Validacions

### ISSUE THREAD

**Issue by jeanmisslin** [gdsa-upc/gdsa-suport#82]
Estem intentant dur a terme les validacions dels rankings i ens trobem que l'arxiu 'annotation.txt' corresponent al conjunt d'imatges de validació no hi és.

Ens hem adonat que aquest arxiu ens venia donat per al conjunt d'entrenament dins del zip 'TB2016' i no sabem com generar-lo.

És possible avaluar el ranking sense aquest arxiu?

**Comment by rogertorresric** [comment]
Nosaltres també ens trobem amb aquets problema.

**Comment by Llado22** [comment]
idem

**Comment by Gerard93** [comment]
desde global piczam computering entertainment company ho vam solucionar creant el nostre propi arxiu annotation.txt buit

**Comment by xavigiro** [comment]
Tal com hem parlat avui a classe, hem acordat que de cara als propers lliuraments a classe treballareu nomes amb les particions d'[entrenament i validació del Terrassa Buildings 900 (1.5G)](https://imatge.upc.edu/web/sites/default/files/projects/1634/public/terrassa-buildings/terrassa900-trainval.zip). Aquestes dades tenen la "pega" que no estan redimensionades, així que hauríeu de preprocessar les imatges per fer-les més petites i així no tindreu tants problemes de càlcul. Recordeu que es van donar diverses alternatives a classe per fer aquest redimensionat, i que també en tenim un exemple de com fer-ho amb Python als mateixos scripts.

El problema de fons és que les anotacions que tinc per la base de dades de 2016 estan en format Kaggle, que és una competició que preparareu de cara a l'examen final. Aquí teniu la [web](https://www.kaggle.com/c/terrassa-buildings-2016) de l'any passat. Participar-hi requerirà que canvieu el format de les dades de sortida, un pas que no vull que adreceu ara. Us donaré detalls de com fer-ho a la darrera sessió.
