### ISSUE TITLE
error team2K-LERA dimensiones

### ISSUE THREAD

**Issue by irenenus** [gdsa-upc/gdsa-suport#83]
Hola!

Seguimos teniendo el error en el traincodebook al llamar la función y lo necesitamos para poder visualizar los resultados de los bow. [https://github.com/gdsa-upc/K-LERA/blob/master/Semana4_ok/get_features.py](url)
Hemos intentado solucionarlo con el reshape y el xfeatures2d y sigue sin funcionar.

Gracias

**Comment by Daniel-dMialdea** [comment]
Al intentar usar el xfeatures2d no nos encuentra el módulo. Lo hemos intentado instalar pero no hemos podido. Creemos que la matriz se nos crea mal porque cuando imprimimos el tamaño nos sale (3,).
![seleccion_011](https://user-images.githubusercontent.com/33546436/33804877-593a5b8c-ddae-11e7-9ca7-5f642f765e78.png)
