### ISSUE TITLE
Lliurament de la presentació oral de la sessió 6

### ISSUE THREAD

**Issue by xavigiro** [gdsa-upc/gdsa-suport#84]
Publiqueu les presentacions orals de l'últim dia de classe responent a aquest fil, indicant a quin equip pertany i proporcionant un enllaç cap a la vostra presentació.

Recordeu que teniu les instruccions en [aquest document](https://docs.google.com/presentation/d/1__lokTXEYe6VSg-iwNJozcqfcVTDciWcIoffk_DArHc/edit?usp=sharing).

**Comment by CasassasOscar** [comment]
Presentació del GRUP 4:[ enllaç ](https://docs.google.com/presentation/d/1jx_p-U8CaXxFm8CJpuD33IXFeWHBLOKg_PWL3BnBmtQ/edit?usp=sharing)

**Comment by AlexBruBuxo** [comment]
Presentació del GRUP 3: [enllaç](https://drive.google.com/open?id=18Bmu1HvoLsHh8M7bptjayD48c5kqEg_5TyZapLhxPFQ)

**Comment by irenenus** [comment]
Presentación K-LERA (Grupo 2): [enllaç](https://prezi.com/p/gmsrj60gl00d/)

**Comment by jeanmisslin** [comment]
Presentació EZficy (Grup 1) : [enllaç](https://github.com/gdsa-upc/2017-EZficy/blob/master/Presentaci%C3%B3n.pptx)

**Comment by Gerard93** [comment]
Presentació PicZam (Grup5) : [enllaç](https://docs.google.com/presentation/d/1zEfPpcylO7mxTPtdNnmPrdUxnZaU522jfSPB3CZjZ5s/edit#slide=id.p)

**Comment by lgotarra** [comment]
Presentació Laura Gotarra, Marta Agüeros: [enllaç](https://drive.google.com/file/d/1_Ihe5vcYOAU0Y5uXRsmFVyw_OVtKaZbt/view?usp=sharing)

**Comment by clarabronsten** [comment]
Presentació Team 6: https://docs.google.com/presentation/d/1K7hqof6CKwmd38c1e4I9troF07VfxfxRmuZBuucna_g/edit#slide=id.g2ca07d9949_0_141

**Comment by xavigiro** [comment]
L'Eva Mohedano us proposa a tots i totes que utilitzeu el [virtualenv](https://virtualenv.pypa.io/en/stable/).
