### ISSUE TITLE
Lliurament de la presentació oral per l'examen de projecte 2017

### ISSUE THREAD

**Issue by xavigiro** [gdsa-upc/gdsa-suport#85]
Responeu a aquest missatge amb un enllaç cap a la vostra presentació del dia de l'examen de projecte del quadrimestre de tardor 2017.

**Comment by mariahuto** [comment]
https://docs.google.com/presentation/d/1-ahMWyf83hR0l0wnmuGKv8Yx61AmP1ZWI-tAX0VKcS4/edit?usp=sharing

**Comment by arroxo7** [comment]
https://prezi.com/view/75IhAi1LUjTE6IK8w53E/

**Comment by CasassasOscar** [comment]
GRUP 4-1: [enllaç ](https://docs.google.com/presentation/d/1dnjRONY-lxGA4fymReyHdHTocoXAsQoi8bI1UpIzqFk/edit?usp=sharing)

**Comment by Gerard93** [comment]
[https://prezi.com/view/28iiznzHgW2Vz2eQvTaL/](url)

**Comment by lgotarra** [comment]
Grup 4.2: [presentació](https://docs.google.com/presentation/d/1ztlnew7zyolQwt-shvUDx9rWi0mGs-dUFHk3v_IRLaI/edit?usp=sharing)

**Comment by Llado22** [comment]
https://docs.google.com/presentation/d/1e2lr0kiZSSiAg-iMVf6IIxBebRjuxnZe1dhYTjzb6Ak/edit#slide=id.p

**Comment by jeanmisslin** [comment]
https://drive.google.com/open?id=1Ft5sFaPrS-epWdmzAhd9by-T3rVK9jrS
