### ISSUE TITLE
Instància VM

### ISSUE THREAD

**Issue by manelsalva** [gdsa-upc/gdsa-suport#87]
Hola, m'he trobat amb el problema que m'obliga a demanar una gpu per a fer una instància de vm, a algú li ha deixat triar la opció de no agafar gpu?

**Comment by noe** [comment]
Acabo de fer la prova i m'ha permès crear la màquina sense GPUs (seleccionant "None").

Pots posar una captura de pantalla per diagnosticar millor el problema?

**Comment by manelsalva** [comment]
![imagen](https://user-images.githubusercontent.com/43412429/48541689-7b4e6b80-e8bd-11e8-880c-549fa2cdb017.png)

**Comment by noe** [comment]
Aquest és el panell de selecció del nombre de CPUs. El de GPUs està una mica més a baix.

**Comment by manelsalva** [comment]
Més a baix em surt aixo:
![imagen](https://user-images.githubusercontent.com/43412429/48543902-c4ed8500-e8c2-11e8-91dc-aec076e63958.png)

**Comment by noe** [comment]
Amb el botó "Customize" (a la dreta de la RAM) es mostra el diàleg on apareix la configuració de GPUs.

**Comment by manelsalva** [comment]
Vale d'acord gracies,
llavors quan tenim aquesta pantalla quina és la tria més adeqüada per un projecte com aquest?
![imagen](https://user-images.githubusercontent.com/43412429/48544828-c1f39400-e8c4-11e8-9af3-46b9d923e944.png)
Moltes gràcies

**Comment by noe** [comment]
Jo crec que amb 4 CPUs i 6Gb de RAM hauria de ser suficient.

**Comment by xavigiro** [comment]
Heu aconseguit posar la instància en marxa ?

**Comment by manelsalva** [comment]
El nostre grup si, i diria que la resta tambe, pero hem tingut altres problemes amb la conexió de pycharm i google cloud que estan a un altre issue
