### ISSUE TITLE
Problema amb la llibreria OpenCV

### ISSUE THREAD

**Issue by AVillegas8** [gdsa-upc/gdsa-suport#88]
Tinc un problema amb l'editor Pycharm, i és que no em reconeix la llibreria OpenCV, i quan faig 'import cv2' em diu que no hi ha cap mòdul anomenat cv2. He estat buscant solucions però cap de les que he provat m'ha funcionat. Algú sap cop arreglar el problema?

**Comment by noe** [comment]
En File -> Settings -> Project interpreter pots veure les llibreries que hi ha instal·lades en l'entorn que estigui fent servir PyCharm. Assegura't que la llibreria aquest en la llista. Si no està, des d'aquí pots també instal·lar-la amb el botó '+'.

**Comment by AVillegas8** [comment]
El problema esta en que no em deixa instalar-la. Quan ho intento em surt el missatge d'error:
'Could not find a version that satisfies the requirement cv2 (from versions: )
No matching distribution found for cv2'

**Comment by noe** [comment]
En el fitxer readme d'aquest projecte estan les instruccions a seguir per instal·lar openCV 2.4.x : https://github.com/gdsa-upc/gdsa-suport#requirements

Has seguit les instruccions per instal·lar-la des del source o amb el package manager de canopy?

**Comment by xavigiro** [comment]
Està resolt ja aquest problema ? Crec que ho vam resoldre utilitzant la instància de GCloud optimitzada per a Deep Learning. Correcte ? Si és així, si us plau tanqueu el tiquet.
