### ISSUE TITLE
Google Cloud Platform

### ISSUE THREAD

**Issue by punti05** [gdsa-upc/gdsa-suport#89]
Estem intentant crear un vincle amb el compte de correu creat per el nostre equip: equip05.gdsa.2018@gmail.com
Però previament, hem vinculat el compte d'un dels membres de l'equip al projecte, pensant que podriem fer-ho tots, però no és així. Hem vist que, com que no som propietaris del projecte, no podem modificar les persones vinculades a aquest, com podem modificar-ho per utilitzar el compte comú?

**Comment by rodrigoarcos** [comment]
Nos ha pasado lo mismo. No sabemos cómo incluir a miembros de nuestro equipo en el proyecto.

**Comment by noe** [comment]
Si en el menú de la consola de Google Cloud vais a IAM & Admin --> IAM , veréis los permisos de los proyectos (si tenéis varios proyectos, podéis seleccionar uno concreto mediante el desplegable de la parte de arriba de la pantalla).

El usuario que creó el proyecto debería tener el rol "Owner" y poder añadir nuevos usuarios (con el botón +Add de arriba) y modificar los permisos (dándole al botón del lápiz junto al usuario concreto).

Por tanto, si entráis con la cuenta del compañero que creó el proyecto, deberíais poder dar permiso al resto. Si haciendo eso no podéis dar permisos, colgad una captura de la pantalla de IAM para que podamos diagnosticar mejor el problema.

**Comment by xavigiro** [comment]
Està resolt aquest issue ? Si és així, el podeu tancar ?

**Comment by xavigiro** [comment]
Suposo que sí que està resolt. Així que el tanco.
