### ISSUE TITLE
GitHub admins

### ISSUE THREAD

**Issue by rodrigoarcos** [gdsa-upc/gdsa-suport#90]
Después de muchos intentos de añadir a mis compañeros de proyecto a GitHub, me he dado cuenta de que no soy administrador y por ello no puedo añadirlos. ¿Hay alguien que me pueda dar una solución, o hacerme administrador?

**Comment by punti05** [comment]
Si entras en el proyecto de GitHub de tu equipo > Settings > Collaborators&Terms > puedes cambiar los permisos de cada uno de los miembros de tu equipo

**Comment by rodrigoarcos** [comment]
Ni siquiera me sale la pestaña de Settings!

**Comment by xavigiro** [comment]
Ja ho he arreglat. Disculpa, només tenies permisos d'escriptura.
