### ISSUE TITLE
No sabemos adaptar la practica0a a Gcloud

### ISSUE THREAD

**Issue by JudithFont** [gdsa-upc/gdsa-suport#91]
Hola,

Tras muchos intentos fallidos y muchas horas buscando, no hemos sido capaces de adaptar la práctica 0a a un script que corra en GCloud desde el editor PyCharm.

Hemos instalado Google Cloud sdk para intentar subir el proyecto creado en PyCharm con los comandos:
`gcloud init`
`gcloud app deploy --project ID_del_projecto`
`gcloud browse`

Solo nos hemos encontrado con pantallas de error.

Creemos que es así como debería subirse el código a Google Cloud Platform,  y si no es así nos gustaría una explicación de cómo hacerlo.

También estamos teniendo problemas instalando Opencv2, y no hemos encontrado manera de instalarlo ni por el source ni por el Project Interpreter.

Muchas gracias

**Comment by Zhomas06** [comment]
Está siendo bastante caótico  el inicio del proyecto la verdad...

**Comment by manelsalva** [comment]
Nuestro grupo esta igual, alguien lo sabe?

**Comment by rodrigoarcos** [comment]
El nuestro también

**Comment by noe** [comment]
`gcloud app deploy` se utiliza para hacer deployment de apps de Google Cloud App Engine (https://cloud.google.com/appengine/). Esto no es lo que tenemos aquí.

Para transferir ficheros a vuestra instancia, consultad https://cloud.google.com/compute/docs/instances/transfer-files

Sobre los problemas con openCV, ¿podéis detallar los pasos concretos que habéis seguido y los mensajes de error concretos que os han salido?
