### ISSUE TITLE
Dudas con con VM de Google Cloud

### ISSUE THREAD

**Issue by Zhomas06** [gdsa-upc/gdsa-suport#93]
Hemos visto que no podemos trabajar varias personas al mismo tiempo con la VM, querriamos saber si hay alguna forma por la cual podamos utilizar varias personas al mismo tiempo la misma instancia?

**Comment by noe** [comment]
¿Puedes describir en detalle la manera en que intentáis trabajar varias personas al mismo tiempo en la misma instancia?

**Comment by Zhomas06** [comment]
En nuestro caso, debemos trabajar todos los componentes del grupo con el mismo correo. 
Lo que querríamos saber es si podemos trabajar cada uno por separado con la misma cuenta simultaneamente. 
Muchas gracias por tu atención.

**Comment by noe** [comment]
¿Qué problema habéis encontrado al probar a trabajar por separado con la misma cuenta?

**Comment by Zhomas06** [comment]
Cuando por ejemplo yo estoy trabajando y se conecta otra persona a mi me expulsa y la última persona en acceder a la Instancia se queda con ella.
Si no has visto esto antes, da igual, continuaremos haciendolo sin solaparnos entre nosotros
