### ISSUE TITLE
Error al desplegar una instancia con Deep Learning VM

### ISSUE THREAD

**Issue by MarcArriaga** [gdsa-upc/gdsa-suport#94]
Hola,

Si intento desplegar una instancia con Deep Learning VM e intento seleccionar una gpu me salta este error:

<img width="1280" alt="captura de pantalla 2018-11-17 a las 16 20 18" src="https://user-images.githubusercontent.com/43412294/48662616-c9fa3200-ea84-11e8-9264-4eb7cba4274b.png">

> tensorflow-1-vm: {"ResourceType":"compute.v1.instance","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"errors":[{"domain":"usageLimits","message":"Quota 'GPUS_ALL_REGIONS' exceeded. Limit: 0.0 globally.","reason":"quotaExceeded"}],"message":"Quota 'GPUS_ALL_REGIONS' exceeded. Limit: 0.0 globally.","statusMessage":"Forbidden","requestPath":"https://www.googleapis.com/compute/v1/projects/gdsa-2018-equip-6/zones/us-west1-b/instances","httpMethod":"POST"}}

En el caso de no seleccionar una gpu si puedo desplegar la instancia. Hay alguna solución para este problema?

Muchas gracias.

**Comment by noe** [comment]
Si lo volvéis a probar, ¿el error se reproduce sistemáticamente?

**Comment by MarcArriaga** [comment]
He seguido los pasos del otro Issue y he pedido una GPU
