### ISSUE TITLE
Error al crear instancia

### ISSUE THREAD

**Issue by paula3** [gdsa-upc/gdsa-suport#95]
Siguiendo los pasos de la presentación aparece el siguiente error cuándo se crea la instancia.

![captura](https://user-images.githubusercontent.com/44504544/48675661-f0d76780-eb5b-11e8-8259-25b1240cc2a1.PNG)

tensorflow-2-vm: {"ResourceType":"compute.v1.instance","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"errors":[{"domain":"usageLimits","message":"Quota 'GPUS_ALL_REGIONS' exceeded. Limit: 0.0 globally.","reason":"quotaExceeded"}],"message":"Quota 'GPUS_ALL_REGIONS' exceeded. Limit: 0.0 globally.","statusMessage":"Forbidden","requestPath":"https://www.googleapis.com/compute/v1/projects/gdsa-222916/zones/europe-west1-b/instances","httpMethod":"POST"}}

**Comment by noe** [comment]
El error sugiere que tienes una quota de GPUs de 0 para cualquier zona. ¿Se repite sistemáticamente el problema si lo intentas más veces?

**Comment by paula3** [comment]
Si intenro crear más instancias TensorFlow, si me aparece el mismo error:
tensorflow-3-vm: {"ResourceType":"compute.v1.instance","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"errors":[{"domain":"usageLimits","message":"Quota 'GPUS_ALL_REGIONS' exceeded. Limit: 0.0 globally.","reason":"quotaExceeded"}],"message":"Quota 'GPUS_ALL_REGIONS' exceeded. Limit: 0.0 globally.","statusMessage":"Forbidden","requestPath":"https://www.googleapis.com/compute/v1/projects/gdsa-222916/zones/europe-west1-b/instances","httpMethod":"POST"}} 

En cambio, si lo hago de la siguiente manera, ahora me deja crearla pero anteriormente no. (Siguiendo la 2a manera que dice el PowerPoint)

![imagen](https://user-images.githubusercontent.com/44504544/48707019-64ca4c00-ebfe-11e8-8afa-3ed57181afa0.png)

**Comment by noe** [comment]
It is very strange that you have a quota of 0 GPUs. I don't know why you happened to get this quota. In order to request an increase, you can go to IAM & Admin --> Quotas. Look for "GPUs (all regions)" (you can select it in the "Metric" filter) and edit the quota to set it to 1 instead of 0.

**Comment by paula3** [comment]
I think too. Following your steps:
![imagen](https://user-images.githubusercontent.com/44504544/48708137-fab3a600-ec01-11e8-9b67-63bc8720f3eb.png)

**Comment by noe** [comment]
What do you mean with "Following your steps"? Did you manage to request the change in the GPU quota?

**Comment by paula3** [comment]
Ya está solucionado muchas gracias!
