### ISSUE TITLE
Error al extraer descriptores visuales de la capa fc2

### ISSUE THREAD

**Issue by MarcArriaga** [gdsa-upc/gdsa-suport#96]
Hola,

Al ejecutar este comando me da este error:
<img width="849" alt="captura de pantalla 2018-11-19 a las 18 37 44" src="https://user-images.githubusercontent.com/43412294/48724787-74f82080-ec2a-11e8-9650-586453c5b348.png">

Alguna solución?

**Comment by noe** [comment]
¿Qué pasos (detallados) habéis seguido para llegar hasta ahí? ¿Qué cosas habéis investigado antes de no saber cómo seguir?

**Comment by MarcArriaga** [comment]
He creado una libreta en jupyter y he copiado el código de la sesión 4 que nos ha proporcionado Xavi Giró.

Te adjunto una captura de pantalla del código entero, cambiando solo una linea que daba error.

Tengo la sensación de que no existe la capa fc2.

<img width="1278" alt="captura de pantalla 2018-11-20 a las 11 42 24" src="https://user-images.githubusercontent.com/43412294/48768454-5e4cda80-ecb9-11e8-8aab-1febca1703cb.png">

**Comment by noe** [comment]
¿ Puedes poner aquí la salida de `base_model.summary()` ?

**Comment by MarcArriaga** [comment]
Ya lo comentamos con Xavi en clase y comprobamos que no existia la capa fc2 en ResNet50, por tanto utilizaremos otro modelo.

Muchas gracias!
