### ISSUE TITLE
Error al instalar Google Cloud SDK

### ISSUE THREAD

**Issue by JudithFont** [gdsa-upc/gdsa-suport#98]
![image](https://user-images.githubusercontent.com/43608773/48769647-770abf80-ecbc-11e8-8110-b4bf4c5fd514.png)
![error google cloud](https://user-images.githubusercontent.com/43608773/48769790-d8329300-ecbc-11e8-9cf0-d5a4aab00a24.JPG)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 21: ordinal not in range(128)
Failed to install.

Al intentar instalar Google Cloud Installer se produce un error y no se como arregrarlo.

**Comment by noe** [comment]
This is a possible solution: https://stackoverflow.com/a/50495526/674487

**Comment by JudithFont** [comment]
No entiendo lo que quiere que haga. Tengo el pyhton 2.7 instalado correctamente.

**Comment by noe** [comment]
Me refería a esto:
![image](https://user-images.githubusercontent.com/4972/48774178-c4d9f480-ecc9-11e8-8857-54ee09aa5ac7.png)

**Comment by Zhomas06** [comment]
Hola buenas tardes,
yo he tenido el mismo problema pero un tanto diferente, he encontrado la solución.
El error en su caso dice que ascii no puede leer el 0xf1. Este valor es el de ñ, esto quiere decir que el c:\Users\...ñ... y el programa es incapaz de leerlo.
Yo lo he averiguado a que en mi nombre de ordenador es Tomás y por lo tanto c:\Users\Tomás . A mi me salía el error de que ascii no podía leer el caracter 0xe1, que en ascii es á.
Conclusión si tienes un nombre con algún acento o ñ , el programa no se instalará ya que no puede reconocer este caracter.

**Comment by noe** [comment]
¿ @JudithFont has probado lo que comenta @Zhomas06 ?

**Comment by JudithFont** [comment]
Si y ya esta solucionado, muchas gracias
