### ISSUE TITLE
Dubtes a l'hora de pujar les fotos

### ISSUE THREAD

**Issue by manelsalva** [gdsa-upc/gdsa-suport#99]
Hola, no acabo d'entendre com pujar les fotografies a la maquina virtual, no se si s'han de pujar al jupyter o a la maquina directament, i si s'ha de pujar a la maquina com s'accedeix desde el jupyter?

**Comment by manelsalva** [comment]
![captura](https://user-images.githubusercontent.com/43412429/48787109-7720b480-ece8-11e8-97e0-ed877810164b.PNG)
Em dona aquest error si l'intento penjar amb gcloud

**Comment by noe** [comment]
¿Podéis probar con esto: https://stackoverflow.com/a/49587145/674487 ?

**Comment by MARTGOMEZ** [comment]
@noe ¿es necesario crear un modelo? No encontramos la forma de linkar la base de datos de las fotos, ya subidas, a nuestro código para poder extraer los descriptores.
